package servicedef

import (
	"strings"
)

// renderLaunchd writes a launchd job description. It is a file, not a load: the
// operator places it under /Library/LaunchDaemons (or a user LaunchAgents
// directory) and runs launchctl themselves, so the generated job can be
// reviewed and version-controlled before anything on the machine changes.
func renderLaunchd(spec Spec) []byte {
	var out strings.Builder
	out.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
	out.WriteString(`<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">` + "\n")
	out.WriteString("<!-- Generated by armadra-host install. Nothing was registered or started. -->\n")
	out.WriteString(`<plist version="1.0">` + "\n")
	out.WriteString("<dict>\n")
	plistString(&out, 1, "Label", spec.Identifier)
	indent(&out, 1)
	out.WriteString("<key>ProgramArguments</key>\n")
	indent(&out, 1)
	out.WriteString("<array>\n")
	plistValue(&out, 2, spec.Executable)
	for _, argument := range spec.Arguments() {
		plistValue(&out, 2, argument)
	}
	indent(&out, 1)
	out.WriteString("</array>\n")
	plistString(&out, 1, "UserName", spec.RunAs)
	plistString(&out, 1, "WorkingDirectory", spec.WorkingDir)
	plistString(&out, 1, "StandardOutPath", spec.LogPath)
	plistString(&out, 1, "StandardErrorPath", spec.LogPath)
	plistBool(&out, 1, "RunAtLoad", true)
	plistBool(&out, 1, "KeepAlive", true)
	// The Host exits on SIGTERM after draining. ProcessType Background keeps
	// launchd from throttling it as an interactive job.
	plistString(&out, 1, "ProcessType", "Background")
	if len(spec.Environment) > 0 {
		indent(&out, 1)
		out.WriteString("<key>EnvironmentVariables</key>\n")
		indent(&out, 1)
		out.WriteString("<dict>\n")
		for _, entry := range spec.Environment {
			name, value, _ := strings.Cut(entry, "=")
			plistString(&out, 2, name, value)
		}
		indent(&out, 1)
		out.WriteString("</dict>\n")
	}
	out.WriteString("</dict>\n")
	out.WriteString("</plist>\n")
	return []byte(out.String())
}

func indent(out *strings.Builder, depth int) {
	for range depth {
		out.WriteString("  ")
	}
}

// plistString writes one <key>/<string> pair at the requested depth.
func plistString(out *strings.Builder, depth int, key, value string) {
	indent(out, depth)
	out.WriteString("<key>" + escapeXML(key) + "</key>\n")
	plistValue(out, depth, value)
}

func plistValue(out *strings.Builder, depth int, value string) {
	indent(out, depth)
	out.WriteString("<string>" + escapeXML(value) + "</string>\n")
}

func plistBool(out *strings.Builder, depth int, key string, value bool) {
	indent(out, depth)
	out.WriteString("<key>" + escapeXML(key) + "</key>\n")
	indent(out, depth)
	if value {
		out.WriteString("<true/>\n")
	} else {
		out.WriteString("<false/>\n")
	}
}

// escapeXML is deliberately explicit rather than encoding/xml's escaper: the
// output must stay byte-identical across Go versions for the determinism the
// install command promises.
func escapeXML(value string) string {
	replacer := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;", "'", "&apos;")
	return replacer.Replace(value)
}
