package servicedef

import (
	"path/filepath"
	"sort"
	"strings"
)

// renderSystemd writes a system service unit. The unit is only written to disk:
// this command never runs systemctl, so it never enables, starts or reloads
// anything. The operator installs the file and decides when the Host starts.
func renderSystemd(spec Spec) []byte {
	var out strings.Builder
	out.WriteString("# Generated by armadra-host install. Nothing was registered or started.\n")
	out.WriteString("# Review, copy into the system unit directory, then enable it yourself.\n")
	out.WriteString("\n[Unit]\n")
	out.WriteString("Description=Armadra Host (" + systemdValue(spec.Identifier) + ")\n")
	out.WriteString("Documentation=https://github.com/yovinchen/Armadra\n")
	out.WriteString("After=network-online.target\n")
	out.WriteString("Wants=network-online.target\n")

	out.WriteString("\n[Service]\n")
	out.WriteString("Type=simple\n")
	out.WriteString("ExecStart=" + systemdCommand(spec) + "\n")
	out.WriteString("User=" + systemdValue(spec.RunAs) + "\n")
	out.WriteString("WorkingDirectory=" + systemdValue(spec.WorkingDir) + "\n")
	if spec.LogPath != "" {
		out.WriteString("StandardOutput=append:" + systemdValue(spec.LogPath) + "\n")
		out.WriteString("StandardError=append:" + systemdValue(spec.LogPath) + "\n")
	} else {
		out.WriteString("StandardOutput=journal\n")
		out.WriteString("StandardError=journal\n")
	}
	out.WriteString("Restart=on-failure\n")
	out.WriteString("RestartSec=5\n")
	// The Host drains HTTP and releases its directory lock on SIGTERM; give it
	// room to finish rather than killing sessions mid-write.
	out.WriteString("KillSignal=SIGTERM\n")
	out.WriteString("TimeoutStopSec=30\n")
	for _, entry := range spec.Environment {
		out.WriteString("Environment=" + systemdEnvironment(entry) + "\n")
	}

	// Hardening is limited to directives that hold for a Host that supervises a
	// Worker running the owner's own commands in their workspaces. ProtectHome
	// and ProtectSystem=strict are deliberately absent: they would hide the
	// checkouts the Worker is expected to read and write.
	out.WriteString("\n# Hardening. ProtectHome / ProtectSystem=strict are intentionally not set:\n")
	out.WriteString("# the Worker runs the owner's commands in their own workspaces.\n")
	out.WriteString("NoNewPrivileges=true\n")
	out.WriteString("ProtectSystem=full\n")
	out.WriteString("ProtectKernelTunables=true\n")
	out.WriteString("ProtectKernelModules=true\n")
	out.WriteString("ProtectControlGroups=true\n")
	out.WriteString("RestrictSUIDSGID=true\n")
	out.WriteString("RestrictRealtime=true\n")
	out.WriteString("LockPersonality=true\n")
	if paths := readWritePaths(spec); len(paths) > 0 {
		quoted := make([]string, 0, len(paths))
		for _, path := range paths {
			quoted = append(quoted, systemdQuote(path))
		}
		out.WriteString("ReadWritePaths=" + strings.Join(quoted, " ") + "\n")
	}
	out.WriteString("UMask=0077\n")

	out.WriteString("\n[Install]\n")
	out.WriteString("WantedBy=multi-user.target\n")
	return []byte(out.String())
}

// readWritePaths lists the directories the Host must write even under
// ProtectSystem=full. Duplicates and nested duplicates are collapsed so the
// rendered line is stable.
func readWritePaths(spec Spec) []string {
	unique := map[string]bool{}
	for _, path := range []string{spec.DataDir, spec.WorkingDir, spec.EndpointsDir, spec.WorkerStateDir, filepath.Dir(spec.LogPath)} {
		if path != "" && path != "." {
			unique[path] = true
		}
	}
	paths := make([]string, 0, len(unique))
	for path := range unique {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	return paths
}

// systemdCommand renders ExecStart with absolute paths and every argument
// quoted, so a value containing a space cannot split into two arguments.
func systemdCommand(spec Spec) string {
	parts := []string{systemdQuote(spec.Executable)}
	for _, argument := range spec.Arguments() {
		parts = append(parts, systemdQuote(argument))
	}
	return strings.Join(parts, " ")
}

func systemdQuote(value string) string {
	return `"` + systemdEscape(value) + `"`
}

// systemdEscape is the inner part of systemdQuote: what a value looks like
// inside the rendered file, which is also what Owns has to search for. Percent
// is doubled because systemd expands specifiers inside quotes too.
func systemdEscape(value string) string {
	return strings.NewReplacer(`\`, `\\`, `"`, `\"`, "%", "%%").Replace(value)
}

func systemdEnvironment(entry string) string {
	name, value, _ := strings.Cut(entry, "=")
	return name + "=" + systemdQuote(value)
}

// systemdValue escapes a bare directive value. Normalize already refused
// control characters, so only percent needs doubling to survive specifier
// expansion.
func systemdValue(value string) string {
	return strings.ReplaceAll(value, "%", "%%")
}
