package servicedef

import (
	"strings"
)

// renderWindows writes a reviewable installation script. Windows has no
// declarative unit file for a plain service, so the definition is the exact
// sc.exe command line an administrator would run — and this command only writes
// it out. Nothing is registered, enabled or started: the operator runs the
// script, supplies the account password to Windows itself, and stays in
// control of when the service appears.
func renderWindows(spec Spec) []byte {
	var out strings.Builder
	out.WriteString("@echo off\r\n")
	out.WriteString("REM Generated by armadra-host install. NOTHING WAS INSTALLED.\r\n")
	out.WriteString("REM This file is a reviewable definition, not an installation.\r\n")
	out.WriteString("REM Run it from an elevated prompt to register the service yourself.\r\n")
	out.WriteString("REM No account credential is written here: sc.exe asks for it, or you\r\n")
	out.WriteString("REM grant the account \"Log on as a service\" and supply it yourself.\r\n")
	out.WriteString("\r\n")
	out.WriteString("set ARMADRA_SERVICE=" + windowsPlain(spec.Identifier) + "\r\n")
	out.WriteString("set ARMADRA_ACCOUNT=" + windowsPlain(spec.RunAs) + "\r\n")
	out.WriteString("set ARMADRA_WORKDIR=" + windowsPlain(spec.WorkingDir) + "\r\n")
	out.WriteString("set ARMADRA_LOG=" + windowsPlain(spec.LogPath) + "\r\n")
	for _, entry := range spec.Environment {
		name, value, _ := strings.Cut(entry, "=")
		out.WriteString("REM environment: " + windowsPlain(name) + "=" + windowsPlain(value) + "\r\n")
	}
	out.WriteString("\r\n")
	out.WriteString("sc.exe create \"%ARMADRA_SERVICE%\" binPath= " + windowsQuote(commandLine(spec)) +
		" obj= \"%ARMADRA_ACCOUNT%\" start= auto DisplayName= \"Armadra Host\"\r\n")
	out.WriteString("sc.exe description \"%ARMADRA_SERVICE%\" \"Armadra Host background service\"\r\n")
	// Restart the service on failure, matching the Unix definitions: three
	// bounded retries before Windows gives up rather than an endless loop.
	out.WriteString("sc.exe failure \"%ARMADRA_SERVICE%\" reset= 86400 actions= restart/5000/restart/5000/restart/30000\r\n")
	out.WriteString("\r\n")
	out.WriteString("REM The Host writes its own diagnostics to %ARMADRA_LOG%.\r\n")
	out.WriteString("REM Start it when you are ready:  sc.exe start \"%ARMADRA_SERVICE%\"\r\n")
	return []byte(out.String())
}

// commandLine is the full program invocation, quoted the way the Windows
// command line parser reads it back into argv.
func commandLine(spec Spec) string {
	parts := []string{windowsArgument(spec.Executable)}
	for _, argument := range spec.Arguments() {
		parts = append(parts, windowsArgument(argument))
	}
	return strings.Join(parts, " ")
}

// windowsArgument quotes an argument only when it needs it, so a plain flag
// stays readable in the generated script.
func windowsArgument(value string) string {
	if value != "" && !strings.ContainsAny(value, " \t\"") {
		return value
	}
	return `"` + strings.ReplaceAll(value, `"`, `\"`) + `"`
}

// windowsQuote wraps the binPath value, doubling embedded quotes the way sc.exe
// expects them inside its own argument.
func windowsQuote(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `""`) + `"`
}

// windowsPlain refuses nothing on its own: Normalize already rejected control
// characters, and a batch `set` line takes the rest verbatim. Percent is the
// one character the interpreter would expand, so it is neutralised.
func windowsPlain(value string) string {
	return strings.ReplaceAll(value, "%", "%%")
}
