//! Detecting a usable tmux and rendering the configuration it is started
//! with.

use super::*;

/// The oldest tmux that has `new-session -e` (per-session environment) and the
/// `window-size` option this design depends on.
pub const MINIMUM_VERSION: (u32, u32) = (3, 2);

/// Regenerated whenever the rendered configuration changes, so an existing conf
/// from an older build is overwritten rather than trusted.
///
/// `{terminal}` is filled in by [`default_terminal`]: `tmux-256color` is the
/// right answer, but its terminfo entry is missing on stock macOS and on
/// minimal Linux images, and a `default-terminal` that has no terminfo entry
/// makes every CLI fall back to dumb rendering (plan §18.3, TERM row).
pub(super) const CONF_TEMPLATE: &str = "\
# Generated by Armadra. Edits are overwritten (plan \u{a7}15.3).
set -g prefix None
set -g status off
set -g history-limit 5000
set -g escape-time 0
set -g allow-passthrough on
set -g set-clipboard on
set -g default-terminal \"{terminal}\"
set -ga terminal-overrides \",*:Tc\"
set -ga terminal-features \",xterm-256color:RGB\"
set -g window-size latest
set -g aggressive-resize on
#
# Selection and clipboard (plan \u{a7}18.3 amendment, 鼠标 / 剪贴板 rows).
#
# `mouse off` is the whole fix for \"clicking types garbage and I cannot copy\":
# with `mouse on` tmux turns SGR mouse reporting on *in the client*, so xterm
# stops doing native text selection (it forwards every press as \\e[<0;x;yM
# instead) and any app that does not consume those bytes echoes them. Turning
# it off gives selection back to xterm. Inner apps are unaffected: when a pane
# asks for mouse tracking itself (vim, htop), tmux forwards that request to the
# client, so they still get their mouse events.
set -g mouse off
# Same class of problem: `focus-events on` makes tmux ask the client for
# \\e[?1004h, and the \\e[I / \\e[O reports leak as `[I` / `[O` into panes that
# do not consume them.
set -g focus-events off
# Keep the CLIENT out of the alternate screen. tmux then draws into xterm's
# normal buffer, so tmux's scrollback lands in xterm's own scrollback: the
# wheel scrolls history and drag-selection works without ever entering
# copy-mode. Cost: a full redraw (reattach, resize) appends a duplicate screen
# to the scrollback, which is the accepted trade.
set -ga terminal-overrides \",*:smcup@:rmcup@\"
# Let an inner app's OSC 52 reach the outer terminal. `set-clipboard on` alone
# is not enough: tmux only forwards the sequence when the client's terminal is
# known to have the `clipboard` feature.
set -as terminal-features \",xterm*:clipboard\"
# Without these tmux swallows the pane's OSC 0/2 and never re-emits one to the
# attached client, so the node title could never follow the running command
# (plan \u{a7}18.3, 标题 row). `#T` is the pane title, i.e. exactly what the CLI set.
set -g set-titles on
set -g set-titles-string \"#T\"
set -g exit-empty on
set -g exit-unattached off
set -g remain-on-exit off
set -g detach-on-destroy on
";

/// The terminfo entry tmux should claim inside the session.
///
/// `infocmp` is the only reliable probe: the entry can be present in
/// `/usr/share/terminfo`, in `~/.terminfo`, or nowhere at all. Falling back to
/// `screen-256color` keeps 256 colours (true colour still arrives through
/// `terminal-overrides ,*:Tc`), which is strictly better than a broken
/// `tmux-256color`.
pub(super) fn default_terminal() -> &'static str {
    let found = std::process::Command::new("infocmp")
        .arg("tmux-256color")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|status| status.success())
        .unwrap_or(false);
    if found {
        "tmux-256color"
    } else {
        "screen-256color"
    }
}

/// The conf as it should be on disk right now.
pub(super) fn rendered_conf() -> String {
    CONF_TEMPLATE.replace("{terminal}", default_terminal())
}

#[derive(Debug, Clone, Default)]
pub struct TmuxDetection {
    pub version: Option<String>,
    pub usable: bool,
    /// Why tmux is not usable; `None` when it is.
    pub reason: Option<String>,
}

/// `tmux -V`. Never panics and never blocks for long: a missing binary is the
/// normal case on a machine that has not installed tmux.
pub fn detect() -> TmuxDetection {
    if cfg!(windows) {
        return TmuxDetection {
            version: None,
            usable: false,
            reason: Some("tmux is not supported on Windows".into()),
        };
    }
    let Ok(output) = std::process::Command::new("tmux").arg("-V").output() else {
        return TmuxDetection {
            version: None,
            usable: false,
            reason: Some("tmux was not found on PATH".into()),
        };
    };
    if !output.status.success() {
        return TmuxDetection {
            version: None,
            usable: false,
            reason: Some("tmux -V failed".into()),
        };
    }
    let banner = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    let version = banner
        .split_whitespace()
        .next_back()
        .unwrap_or_default()
        .to_owned();
    match parse_version(&version) {
        Some(parsed) if parsed >= MINIMUM_VERSION => TmuxDetection {
            version: Some(version),
            usable: true,
            reason: None,
        },
        Some(_) => TmuxDetection {
            reason: Some(format!(
                "tmux {version} is older than {}.{}",
                MINIMUM_VERSION.0, MINIMUM_VERSION.1
            )),
            version: Some(version),
            usable: false,
        },
        // `master` / `next-3.6`: unversioned builds are newer than the floor.
        None => TmuxDetection {
            version: Some(version),
            usable: true,
            reason: None,
        },
    }
}

/// `3.2a` -> `(3, 2)`; `master` -> `None`.
pub(super) fn parse_version(version: &str) -> Option<(u32, u32)> {
    let digits: String = version
        .chars()
        .skip_while(|character| !character.is_ascii_digit())
        .collect();
    let mut parts = digits.split('.');
    let major = parts.next()?.parse::<u32>().ok()?;
    let minor: String = parts
        .next()
        .unwrap_or("0")
        .chars()
        .take_while(char::is_ascii_digit)
        .collect();
    Some((major, minor.parse::<u32>().unwrap_or(0)))
}

/// Writes `tmux.conf` when it is missing or stale, and locks the directory down
/// to 0700 / the file to 0600: whoever can reach the socket owns every session.
pub fn ensure_conf(conf: &Path) -> AppResult<()> {
    if let Some(parent) = conf.parent() {
        std::fs::create_dir_all(parent)?;
        paths::harden_directory(parent);
    }
    let wanted = rendered_conf();
    let current = std::fs::read_to_string(conf).unwrap_or_default();
    if current != wanted {
        std::fs::write(conf, &wanted)?;
    }
    paths::harden_file(conf);
    Ok(())
}
