import { execFileSync, spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { hardenDirectory, hardenFile } from "../../paths";

/**
 * Detecting a usable tmux and rendering the configuration it is started with.
 *
 * Both are ports of the pre-merge implementation, byte for byte
 * where the bytes are contractual: the conf is written to the same path the
 * Rust Runtime writes, and a machine that ran one yesterday and the other
 * today must not see its options change underneath a live server.
 */

/**
 * The oldest tmux that has `new-session -e` (per-session environment) and the
 * `window-size` option this design depends on.
 */
export const MINIMUM_VERSION: readonly [number, number] = [3, 2];

/**
 * Regenerated whenever the rendered configuration changes, so an existing conf
 * from an older build is overwritten rather than trusted.
 *
 * `{terminal}` is filled in by {@link defaultTerminal}: `tmux-256color` is the
 * right answer, but its terminfo entry is missing on stock macOS and on
 * minimal Linux images, and a `default-terminal` that has no terminfo entry
 * makes every CLI fall back to dumb rendering (contract §18.3, TERM row).
 */
export const CONF_TEMPLATE = `# Generated by Armadra. Edits are overwritten (plan §15.3).
set -g prefix None
set -g status off
set -g history-limit 5000
set -g escape-time 0
set -g allow-passthrough on
set -g set-clipboard on
set -g default-terminal "{terminal}"
set -ga terminal-overrides ",*:Tc"
set -ga terminal-features ",xterm-256color:RGB"
set -g window-size latest
set -g aggressive-resize on
#
# Selection and clipboard (plan §18.3 amendment, 鼠标 / 剪贴板 rows).
#
# \`mouse off\` is the whole fix for "clicking types garbage and I cannot copy":
# with \`mouse on\` tmux turns SGR mouse reporting on *in the client*, so xterm
# stops doing native text selection (it forwards every press as \\e[<0;x;yM
# instead) and any app that does not consume those bytes echoes them. Turning
# it off gives selection back to xterm. Inner apps are unaffected: when a pane
# asks for mouse tracking itself (vim, htop), tmux forwards that request to the
# client, so they still get their mouse events.
set -g mouse off
# Same class of problem: \`focus-events on\` makes tmux ask the client for
# \\e[?1004h, and the \\e[I / \\e[O reports leak as \`[I\` / \`[O\` into panes that
# do not consume them.
set -g focus-events off
# Keep the CLIENT out of the alternate screen. tmux then draws into xterm's
# normal buffer, so tmux's scrollback lands in xterm's own scrollback: the
# wheel scrolls history and drag-selection works without ever entering
# copy-mode. Cost: a full redraw (reattach, resize) appends a duplicate screen
# to the scrollback, which is the accepted trade.
set -ga terminal-overrides ",*:smcup@:rmcup@"
# Let an inner app's OSC 52 reach the outer terminal. \`set-clipboard on\` alone
# is not enough: tmux only forwards the sequence when the client's terminal is
# known to have the \`clipboard\` feature.
set -as terminal-features ",xterm*:clipboard"
# Without these tmux swallows the pane's OSC 0/2 and never re-emits one to the
# attached client, so the node title could never follow the running command
# (plan §18.3, 标题 row). \`#T\` is the pane title, i.e. exactly what the CLI set.
set -g set-titles on
set -g set-titles-string "#T"
set -g exit-empty on
set -g exit-unattached off
set -g remain-on-exit off
set -g detach-on-destroy on
`;

/**
 * The terminfo entry tmux should claim inside the session.
 *
 * `infocmp` is the only reliable probe: the entry can be present in
 * `/usr/share/terminfo`, in `~/.terminfo`, or nowhere at all. Falling back to
 * `screen-256color` keeps 256 colours (true colour still arrives through
 * `terminal-overrides ,*:Tc`), which is strictly better than a broken
 * `tmux-256color`.
 */
export function defaultTerminal(): "tmux-256color" | "screen-256color" {
  const probe = spawnSync("infocmp", ["tmux-256color"], { stdio: "ignore" });
  return probe.status === 0 ? "tmux-256color" : "screen-256color";
}

/** The conf as it should be on disk right now. */
export function renderedConf(terminal: string = defaultTerminal()): string {
  return CONF_TEMPLATE.replaceAll("{terminal}", terminal);
}

export interface TmuxDetection {
  readonly version?: string | undefined;
  readonly usable: boolean;
  /** Why tmux is not usable; absent when it is. */
  readonly reason?: string | undefined;
}

/**
 * `tmux -V`. Never throws and never blocks for long: a missing binary is the
 * normal case on a machine that has not installed tmux.
 */
export function detect(platform: string = process.platform): TmuxDetection {
  if (platform === "win32") {
    return { usable: false, reason: "tmux is not supported on Windows" };
  }
  let banner: string;
  try {
    banner = execFileSync("tmux", ["-V"], { encoding: "utf8" }).trim();
  } catch {
    return { usable: false, reason: "tmux was not found on PATH" };
  }
  const version = banner.split(/\s+/).pop() ?? "";
  const parsed = parseVersion(version);
  if (parsed === undefined) {
    // `master` / `next-3.6`: unversioned builds are newer than the floor.
    return { version, usable: true };
  }
  if (
    parsed[0] > MINIMUM_VERSION[0] ||
    (parsed[0] === MINIMUM_VERSION[0] && parsed[1] >= MINIMUM_VERSION[1])
  ) {
    return { version, usable: true };
  }
  return {
    version,
    usable: false,
    reason: `tmux ${version} is older than ${MINIMUM_VERSION[0]}.${MINIMUM_VERSION[1]}`,
  };
}

/** `3.2a` -> `[3, 2]`; `master` -> `undefined`. */
export function parseVersion(
  version: string,
): readonly [number, number] | undefined {
  const digits = version.replace(/^[^0-9]*/, "");
  const parts = digits.split(".");
  const major = Number.parseInt(parts[0] ?? "", 10);
  if (!Number.isFinite(major) || parts[0] === "") return undefined;
  const minorDigits = (parts[1] ?? "0").match(/^[0-9]*/)?.[0] ?? "";
  const minor = Number.parseInt(minorDigits, 10);
  return [major, Number.isFinite(minor) ? minor : 0];
}

/**
 * Writes `tmux.conf` when it is missing or stale, and locks the directory down
 * to 0700 / the file to 0600: whoever can reach the socket owns every session.
 *
 * "When it is stale" is load-bearing and is asserted by a test: rewriting an
 * identical file on every create would bump its mtime, and the conf is read by
 * a server that may have been started days ago.
 */
export function ensureConf(conf: string, wanted = renderedConf()): void {
  const parent = dirname(conf);
  mkdirSync(parent, { recursive: true });
  hardenDirectory(parent);
  let current = "";
  try {
    current = readFileSync(conf, "utf8");
  } catch {
    // Missing is the normal first run.
  }
  if (current !== wanted) writeFileSync(conf, wanted, "utf8");
  hardenFile(conf);
}
