/**
 * The launcher that makes `out/cli/armadra-hook.js` runnable as a plain
 * command path.
 *
 * Every CLI integration writes an **absolute program path** into its own
 * configuration and runs it with one argument: Claude and Codex write
 * `<path> <agentId>` as a shell command string, Copilot writes `<path>` into
 * an `exec` field that takes no arguments at all, and the opencode / Pi / OMP
 * modules pass `<path>` straight to `spawn`. None of them can carry an
 * environment variable or a second interpreter argument, so the JavaScript
 * bundle cannot be the thing they name.
 *
 * `#!/usr/bin/env node` is not an option either: the only interpreter a
 * packaged install is guaranteed to have is the Electron binary it ships, and
 * a user's machine may have no `node` on `PATH` at all — especially over SSH
 * or inside a tmux session started before any version manager ran.
 *
 * So the installed artefact is a two-line launcher that re-enters that same
 * Electron binary as a Node interpreter:
 *
 * ```sh
 * ELECTRON_RUN_AS_NODE=1 exec "<electron>" "<resources>/cli/armadra-hook.js" "$@"
 * ```
 *
 * On Windows a script launcher is a `.cmd`, and every `.cmd` runs through
 * `cmd.exe`, which reads the command line a second time: `&`, `|`, `%`, `^`
 * and an escaped `"` inside `canvas send --body …` become command separators,
 * variable expansions or a shifted quote state — from Git Bash and PowerShell
 * alike, since both hand a `.cmd` to `cmd.exe`. So on Windows the installed
 * command is `armadra-hook.exe`, a few-kilobyte console program
 * (`windows-launcher.cs`, built by `scripts/hook-launcher.mjs`) that reads
 * `armadra-hook.launch` beside it — runner on the first line, bundle on the
 * second — and passes the caller's command line to the runner untouched. The
 * `.cmd` is still written next to it: configurations installed before the
 * `.exe` existed name it until their next install, and a build without the
 * `.exe` (packaged off Windows, or an unpackaged development tree) falls back
 * to it.
 *
 * Every name contains `armadra-hook`, so the installer's "did we write this
 * entry?" check — a substring test — keeps working, and a person reading their
 * own `settings.json` still sees a recognisable command.
 */

import * as fs from "node:fs";
import * as path from "node:path";

/** The Windows launcher program and the configuration it reads. */
export const WINDOWS_EXE_NAME = "armadra-hook.exe";
export const WINDOWS_LAUNCH_NAME = "armadra-hook.launch";
/** The `cmd.exe` fallback. */
export const WINDOWS_CMD_NAME = "armadra-hook.cmd";

/** File name of the preferred launcher for a platform. */
export function launcherFileName(
  platform: NodeJS.Platform = process.platform,
): string {
  return platform === "win32" ? WINDOWS_EXE_NAME : "armadra-hook";
}

export interface LauncherTarget {
  /** Absolute path of the Electron binary (or any Node-compatible runner). */
  runner: string;
  /** Absolute path of the built `armadra-hook.js` bundle. */
  bundle: string;
  /**
   * The built `armadra-hook.exe` (Windows only). Copied into the launcher
   * directory when it exists; absent, the `.cmd` is the installed command.
   */
  windowsExe?: string;
}

/** Quotes a value for a POSIX `sh` double-quoted string. */
function shQuote(value: string): string {
  return `"${value.replace(/(["$`\\])/g, "\\$1")}"`;
}

/**
 * Quotes a value for a `cmd.exe` double-quoted argument. `cmd` has no escape
 * for `"` inside `"…"`, so a path containing one cannot be launched — better
 * to refuse than to emit a script that silently runs something else.
 */
function cmdQuote(value: string): string {
  if (value.includes('"'))
    throw new Error(`path cannot contain a quote on Windows: ${value}`);
  return `"${value}"`;
}

/** The POSIX launcher. */
export function posixLauncher(target: LauncherTarget): string {
  return [
    "#!/bin/sh",
    "# Armadra hook client. Generated by the installer; edits are overwritten.",
    "#",
    "# The bundle is plain JavaScript, so it needs an interpreter, and the only",
    "# one a packaged install can count on is the Electron binary it ships.",
    "ELECTRON_RUN_AS_NODE=1",
    "export ELECTRON_RUN_AS_NODE",
    `exec ${shQuote(target.runner)} ${shQuote(target.bundle)} "$@"`,
    "",
  ].join("\n");
}

/**
 * What `armadra-hook.exe` reads: the runner, then the bundle, one per line.
 * Neither can contain a line break (Windows file names cannot), and neither a
 * quote — refused for the same reason as in {@link cmdQuote}.
 */
export function windowsLaunchConfig(target: LauncherTarget): string {
  for (const value of [target.runner, target.bundle]) {
    if (/["\r\n]/.test(value))
      throw new Error(`path cannot contain a quote or a line break: ${value}`);
  }
  return `${target.runner}\r\n${target.bundle}\r\n`;
}

/** The Windows `cmd.exe` fallback launcher. */
export function windowsLauncher(target: LauncherTarget): string {
  return [
    "@echo off",
    "rem Armadra hook client. Generated by the installer; edits are overwritten.",
    "setlocal",
    'set "ELECTRON_RUN_AS_NODE=1"',
    `${cmdQuote(target.runner)} ${cmdQuote(target.bundle)} %*`,
    "exit /b %ERRORLEVEL%",
    "",
  ].join("\r\n");
}

/** The launcher text for a platform. */
export function launcherScript(
  target: LauncherTarget,
  platform: NodeJS.Platform = process.platform,
): string {
  return platform === "win32" ? windowsLauncher(target) : posixLauncher(target);
}

/**
 * Writes the launcher into `directory` and returns its absolute path — the
 * path an installer then writes into each CLI's configuration.
 *
 * Rewritten on every install rather than patched, and deterministic, so
 * reinstalling the same version produces the same bytes.
 */
export function writeLauncher(
  directory: string,
  target: LauncherTarget,
  platform: NodeJS.Platform = process.platform,
): string {
  fs.mkdirSync(directory, { recursive: true });
  if (platform !== "win32") {
    const file = path.join(directory, launcherFileName(platform));
    fs.writeFileSync(file, posixLauncher(target), { mode: 0o755 });
    fs.chmodSync(file, 0o755);
    return file;
  }
  const cmd = path.join(directory, WINDOWS_CMD_NAME);
  fs.writeFileSync(cmd, windowsLauncher(target));
  if (target.windowsExe === undefined || !isFile(target.windowsExe)) return cmd;
  const exe = path.join(directory, WINDOWS_EXE_NAME);
  fs.writeFileSync(
    path.join(directory, WINDOWS_LAUNCH_NAME),
    windowsLaunchConfig(target),
  );
  placeExe(target.windowsExe, exe);
  return exe;
}

function isFile(file: string): boolean {
  try {
    return fs.statSync(file).isFile();
  } catch {
    return false;
  }
}

/**
 * Copies the launcher program into place. A hook that is running right now
 * keeps its `.exe` open, and Windows refuses to overwrite a running image but
 * lets it be renamed — so an unchanged file is left alone, and a changed one
 * that is busy is moved aside first. Leftovers from an earlier move are
 * removed on the way (they fail quietly while still running).
 */
function placeExe(source: string, destination: string): void {
  const wanted = fs.readFileSync(source);
  const directory = path.dirname(destination);
  const aside = `${path.basename(destination)}.old-`;
  for (const name of fs.readdirSync(directory)) {
    if (!name.startsWith(aside)) continue;
    try {
      fs.rmSync(path.join(directory, name), { force: true });
    } catch {
      // Still running; the next install gets it.
    }
  }
  try {
    if (wanted.equals(fs.readFileSync(destination))) return;
  } catch {
    // Not there yet.
  }
  try {
    fs.writeFileSync(destination, wanted);
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code !== "EBUSY" && code !== "EPERM") throw error;
    fs.renameSync(destination, `${destination}.old-${process.pid}`);
    fs.writeFileSync(destination, wanted);
  }
}
