/**
 * The launcher that makes `out/cli/armadra-hook.js` runnable as a plain
 * command path.
 *
 * Every CLI integration writes an **absolute program path** into its own
 * configuration and runs it with one argument: Claude and Codex write
 * `<path> <agentId>` as a shell command string, Copilot writes `<path>` into
 * an `exec` field that takes no arguments at all, and the opencode / Pi / OMP
 * modules pass `<path>` straight to `spawn`. None of them can carry an
 * environment variable or a second interpreter argument, so the JavaScript
 * bundle cannot be the thing they name.
 *
 * `#!/usr/bin/env node` is not an option either: the only interpreter a
 * packaged install is guaranteed to have is the Electron binary it ships, and
 * a user's machine may have no `node` on `PATH` at all — especially over SSH
 * or inside a tmux session started before any version manager ran.
 *
 * So the installed artefact is a two-line launcher that re-enters that same
 * Electron binary as a Node interpreter:
 *
 * ```sh
 * ELECTRON_RUN_AS_NODE=1 exec "<electron>" "<resources>/cli/armadra-hook.js" "$@"
 * ```
 *
 * The file is named `armadra-hook` (POSIX) or `armadra-hook.cmd` (Windows), so
 * the installer's "did we write this entry?" check — a substring test for
 * `armadra-hook` — keeps working, and a person reading their own
 * `settings.json` still sees a recognisable command.
 */

import * as fs from "node:fs";
import * as path from "node:path";

/** File name of the launcher for a platform. */
export function launcherFileName(platform: NodeJS.Platform = process.platform): string {
  return platform === "win32" ? "armadra-hook.cmd" : "armadra-hook";
}

export interface LauncherTarget {
  /** Absolute path of the Electron binary (or any Node-compatible runner). */
  runner: string;
  /** Absolute path of the built `armadra-hook.js` bundle. */
  bundle: string;
}

/** Quotes a value for a POSIX `sh` double-quoted string. */
function shQuote(value: string): string {
  return `"${value.replace(/(["$`\\])/g, "\\$1")}"`;
}

/**
 * Quotes a value for a `cmd.exe` double-quoted argument. `cmd` has no escape
 * for `"` inside `"…"`, so a path containing one cannot be launched — better
 * to refuse than to emit a script that silently runs something else.
 */
function cmdQuote(value: string): string {
  if (value.includes('"')) throw new Error(`path cannot contain a quote on Windows: ${value}`);
  return `"${value}"`;
}

/** The POSIX launcher. */
export function posixLauncher(target: LauncherTarget): string {
  return [
    "#!/bin/sh",
    "# Armadra hook client. Generated by the installer; edits are overwritten.",
    "#",
    "# The bundle is plain JavaScript, so it needs an interpreter, and the only",
    "# one a packaged install can count on is the Electron binary it ships.",
    "ELECTRON_RUN_AS_NODE=1",
    "export ELECTRON_RUN_AS_NODE",
    `exec ${shQuote(target.runner)} ${shQuote(target.bundle)} "$@"`,
    "",
  ].join("\n");
}

/** The Windows launcher. */
export function windowsLauncher(target: LauncherTarget): string {
  return [
    "@echo off",
    "rem Armadra hook client. Generated by the installer; edits are overwritten.",
    "setlocal",
    'set "ELECTRON_RUN_AS_NODE=1"',
    `${cmdQuote(target.runner)} ${cmdQuote(target.bundle)} %*`,
    "exit /b %ERRORLEVEL%",
    "",
  ].join("\r\n");
}

/** The launcher text for a platform. */
export function launcherScript(
  target: LauncherTarget,
  platform: NodeJS.Platform = process.platform,
): string {
  return platform === "win32" ? windowsLauncher(target) : posixLauncher(target);
}

/**
 * Writes the launcher into `directory` and returns its absolute path — the
 * path an installer then writes into each CLI's configuration.
 *
 * Rewritten on every install rather than patched, and deterministic, so
 * reinstalling the same version produces the same bytes.
 */
export function writeLauncher(
  directory: string,
  target: LauncherTarget,
  platform: NodeJS.Platform = process.platform,
): string {
  const file = path.join(directory, launcherFileName(platform));
  fs.mkdirSync(directory, { recursive: true });
  fs.writeFileSync(file, launcherScript(target, platform), { mode: 0o755 });
  if (platform !== "win32") fs.chmodSync(file, 0o755);
  return file;
}
