//! The primary backend: a private tmux server (plan §15.3).
//!
//! Every command goes through `tmux -S <data_dir>/tmux.sock -f
//! <data_dir>/tmux.conf`, so the runtime's sessions share nothing with the
//! user's own tmux server or `~/.tmux.conf`. The pane's process is a child of
//! that server, not of the runtime, which is the whole point: closing the app,
//! or crashing it, leaves the agent running and re-attachable.

use std::{
    collections::HashMap,
    path::{Path, PathBuf},
    process::Stdio,
    sync::{
        Arc, Mutex,
        atomic::{AtomicBool, AtomicU64, Ordering},
    },
};

use async_trait::async_trait;
use bytes::Bytes;
use portable_pty::{Child, CommandBuilder, MasterPty, PtySize, native_pty_system};
use tokio::sync::{RwLock, broadcast, mpsc};

use crate::{
    error::{AppError, AppResult},
    paths,
    terminal::backend::{
        AttachHandle, BackendKind, BackendNotice, BackendRef, DetachGuard, ForegroundInfo,
        NoticeSender, OutputPump, SESSION_PREFIX, SessionKey, TerminalBackend, TerminalHandle,
        TerminalSpec, child_commands, child_environment, runtime_fingerprint, sanitize_paste,
        session_name, spawn_input_pump, spawn_output_pump, strip_escapes, tail_lines,
        terminate_tree, trim_captured,
    },
};

/// The oldest tmux that has `new-session -e` (per-session environment) and the
/// `window-size` option this design depends on.
pub const MINIMUM_VERSION: (u32, u32) = (3, 2);

/// Regenerated whenever the rendered configuration changes, so an existing conf
/// from an older build is overwritten rather than trusted.
///
/// `{terminal}` is filled in by [`default_terminal`]: `tmux-256color` is the
/// right answer, but its terminfo entry is missing on stock macOS and on
/// minimal Linux images, and a `default-terminal` that has no terminfo entry
/// makes every CLI fall back to dumb rendering (plan §18.3, TERM row).
const CONF_TEMPLATE: &str = "\
# Generated by Armadra. Edits are overwritten (plan \u{a7}15.3).
set -g prefix None
set -g status off
set -g history-limit 5000
set -g escape-time 0
set -g allow-passthrough on
set -g set-clipboard on
set -g default-terminal \"{terminal}\"
set -ga terminal-overrides \",*:Tc\"
set -ga terminal-features \",xterm-256color:RGB\"
set -g window-size latest
set -g aggressive-resize on
#
# Selection and clipboard (plan \u{a7}18.3 amendment, 鼠标 / 剪贴板 rows).
#
# `mouse off` is the whole fix for \"clicking types garbage and I cannot copy\":
# with `mouse on` tmux turns SGR mouse reporting on *in the client*, so xterm
# stops doing native text selection (it forwards every press as \\e[<0;x;yM
# instead) and any app that does not consume those bytes echoes them. Turning
# it off gives selection back to xterm. Inner apps are unaffected: when a pane
# asks for mouse tracking itself (vim, htop), tmux forwards that request to the
# client, so they still get their mouse events.
set -g mouse off
# Same class of problem: `focus-events on` makes tmux ask the client for
# \\e[?1004h, and the \\e[I / \\e[O reports leak as `[I` / `[O` into panes that
# do not consume them.
set -g focus-events off
# Keep the CLIENT out of the alternate screen. tmux then draws into xterm's
# normal buffer, so tmux's scrollback lands in xterm's own scrollback: the
# wheel scrolls history and drag-selection works without ever entering
# copy-mode. Cost: a full redraw (reattach, resize) appends a duplicate screen
# to the scrollback, which is the accepted trade.
set -ga terminal-overrides \",*:smcup@:rmcup@\"
# Let an inner app's OSC 52 reach the outer terminal. `set-clipboard on` alone
# is not enough: tmux only forwards the sequence when the client's terminal is
# known to have the `clipboard` feature.
set -as terminal-features \",xterm*:clipboard\"
# Without these tmux swallows the pane's OSC 0/2 and never re-emits one to the
# attached client, so the node title could never follow the running command
# (plan \u{a7}18.3, 标题 row). `#T` is the pane title, i.e. exactly what the CLI set.
set -g set-titles on
set -g set-titles-string \"#T\"
set -g exit-empty on
set -g exit-unattached off
set -g remain-on-exit off
set -g detach-on-destroy on
";

/// The terminfo entry tmux should claim inside the session.
///
/// `infocmp` is the only reliable probe: the entry can be present in
/// `/usr/share/terminfo`, in `~/.terminfo`, or nowhere at all. Falling back to
/// `screen-256color` keeps 256 colours (true colour still arrives through
/// `terminal-overrides ,*:Tc`), which is strictly better than a broken
/// `tmux-256color`.
fn default_terminal() -> &'static str {
    let found = std::process::Command::new("infocmp")
        .arg("tmux-256color")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|status| status.success())
        .unwrap_or(false);
    if found {
        "tmux-256color"
    } else {
        "screen-256color"
    }
}

/// The conf as it should be on disk right now.
fn rendered_conf() -> String {
    CONF_TEMPLATE.replace("{terminal}", default_terminal())
}

#[derive(Debug, Clone, Default)]
pub struct TmuxDetection {
    pub version: Option<String>,
    pub usable: bool,
    /// Why tmux is not usable; `None` when it is.
    pub reason: Option<String>,
}

/// `tmux -V`. Never panics and never blocks for long: a missing binary is the
/// normal case on a machine that has not installed tmux.
pub fn detect() -> TmuxDetection {
    if cfg!(windows) {
        return TmuxDetection {
            version: None,
            usable: false,
            reason: Some("tmux is not supported on Windows".into()),
        };
    }
    let Ok(output) = std::process::Command::new("tmux").arg("-V").output() else {
        return TmuxDetection {
            version: None,
            usable: false,
            reason: Some("tmux was not found on PATH".into()),
        };
    };
    if !output.status.success() {
        return TmuxDetection {
            version: None,
            usable: false,
            reason: Some("tmux -V failed".into()),
        };
    }
    let banner = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    let version = banner
        .split_whitespace()
        .next_back()
        .unwrap_or_default()
        .to_owned();
    match parse_version(&version) {
        Some(parsed) if parsed >= MINIMUM_VERSION => TmuxDetection {
            version: Some(version),
            usable: true,
            reason: None,
        },
        Some(_) => TmuxDetection {
            reason: Some(format!(
                "tmux {version} is older than {}.{}",
                MINIMUM_VERSION.0, MINIMUM_VERSION.1
            )),
            version: Some(version),
            usable: false,
        },
        // `master` / `next-3.6`: unversioned builds are newer than the floor.
        None => TmuxDetection {
            version: Some(version),
            usable: true,
            reason: None,
        },
    }
}

/// `3.2a` -> `(3, 2)`; `master` -> `None`.
fn parse_version(version: &str) -> Option<(u32, u32)> {
    let digits: String = version
        .chars()
        .skip_while(|character| !character.is_ascii_digit())
        .collect();
    let mut parts = digits.split('.');
    let major = parts.next()?.parse::<u32>().ok()?;
    let minor: String = parts
        .next()
        .unwrap_or("0")
        .chars()
        .take_while(char::is_ascii_digit)
        .collect();
    Some((major, minor.parse::<u32>().unwrap_or(0)))
}

/// Writes `tmux.conf` when it is missing or stale, and locks the directory down
/// to 0700 / the file to 0600: whoever can reach the socket owns every session.
pub fn ensure_conf(conf: &Path) -> AppResult<()> {
    if let Some(parent) = conf.parent() {
        std::fs::create_dir_all(parent)?;
        paths::harden_directory(parent);
    }
    let wanted = rendered_conf();
    let current = std::fs::read_to_string(conf).unwrap_or_default();
    if current != wanted {
        std::fs::write(conf, &wanted)?;
    }
    paths::harden_file(conf);
    Ok(())
}

struct TmuxClient {
    id: u64,
    master: Mutex<Option<Box<dyn MasterPty + Send>>>,
    child: Mutex<Option<Box<dyn Child + Send + Sync>>>,
    input: mpsc::Sender<Bytes>,
}

impl TmuxClient {
    /// Ends the `tmux attach-session` process. The session keeps running: this
    /// is a detach, not a kill.
    fn detach(&self) {
        if let Ok(mut child) = self.child.lock()
            && let Some(child) = child.as_mut()
        {
            let _ = child.kill();
        }
        if let Ok(mut master) = self.master.lock() {
            *master = None;
        }
    }
}

struct TmuxSession {
    name: String,
    generation: u64,
    clients: Mutex<Vec<Arc<TmuxClient>>>,
    /// Whether the pane is currently scrolled back in copy-mode (plan §18.5).
    ///
    /// Cached here rather than asked from tmux on every keystroke: `write()` is
    /// the hot path for every character the user types, and a `display -p`
    /// round trip per keystroke would be absurd. It is re-synced from
    /// `#{pane_in_mode}` after every scroll, which is the only thing that can
    /// put the pane into the mode in the first place.
    in_copy_mode: AtomicBool,
}

#[derive(Clone)]
pub struct TmuxBackend {
    socket: PathBuf,
    conf: PathBuf,
    sessions: Arc<RwLock<HashMap<SessionKey, Arc<TmuxSession>>>>,
    notices: NoticeSender,
    next_client_id: Arc<AtomicU64>,
}

impl TmuxBackend {
    /// Fails only if the configuration cannot be written; the server itself is
    /// started lazily by the first `new-session`.
    pub fn new(socket: PathBuf, conf: PathBuf, notices: NoticeSender) -> AppResult<Self> {
        ensure_conf(&conf)?;
        Ok(Self {
            socket,
            conf,
            sessions: Arc::new(RwLock::new(HashMap::new())),
            notices,
            next_client_id: Arc::new(AtomicU64::new(1)),
        })
    }

    pub fn with_data_dir(directory: &Path, notices: NoticeSender) -> AppResult<Self> {
        Self::new(
            directory.join("tmux.sock"),
            directory.join("tmux.conf"),
            notices,
        )
    }

    pub fn socket(&self) -> &Path {
        &self.socket
    }

    fn base_args(&self) -> Vec<String> {
        vec![
            // Force UTF-8 regardless of the runtime's locale: a GUI-launched
            // runtime often has no LANG at all, and tmux would then render every
            // multi-byte character (Chinese included) as `_`.
            "-u".into(),
            "-S".into(),
            self.socket.to_string_lossy().into_owned(),
            "-f".into(),
            self.conf.to_string_lossy().into_owned(),
        ]
    }

    async fn run<I, S>(&self, arguments: I) -> AppResult<String>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<std::ffi::OsStr>,
    {
        // The first command starts the server, and the server keeps this
        // environment for every session it will ever create: built, not
        // inherited (see `child_environment`).
        let output = tokio::process::Command::new("tmux")
            .args(self.base_args())
            .args(arguments)
            .env_clear()
            .envs(child_environment())
            .stdin(Stdio::null())
            .output()
            .await
            .map_err(|error| AppError::Internal(format!("Could not run tmux: {error}")))?;
        if !output.status.success() {
            let message = String::from_utf8_lossy(&output.stderr).trim().to_owned();
            return Err(AppError::Internal(format!("tmux failed: {message}")));
        }
        Ok(String::from_utf8_lossy(&output.stdout).into_owned())
    }

    /// `#{pane_in_mode}` — 1 while the pane is in copy-mode.
    async fn pane_in_mode(&self, name: &str) -> bool {
        self.run(["display", "-p", "-t", name, "#{pane_in_mode}"])
            .await
            .map(|out| out.trim() == "1")
            .unwrap_or(false)
    }

    /// Leave copy-mode if we put the pane there, so the next keystroke reaches
    /// the application instead of being eaten as a copy-mode command
    /// (plan §18.5). Cheap when the flag is already clear: no tmux call at all.
    async fn leave_copy_mode(&self, session: &TmuxSession) {
        if !session.in_copy_mode.swap(false, Ordering::SeqCst) {
            return;
        }
        let _ = self
            .run(["send-keys", "-X", "-t", &session.name, "cancel"])
            .await;
    }

    async fn session(&self, key: &SessionKey) -> AppResult<Arc<TmuxSession>> {
        self.sessions
            .read()
            .await
            .get(key)
            .cloned()
            .ok_or_else(|| AppError::NotFound("Terminal session is not running".into()))
    }

    /// Re-adopts a session that this runtime did not create — after a restart,
    /// the tmux server still has it but the in-memory map does not.
    pub async fn adopt(&self, key: &SessionKey, name: &str, generation: u64) {
        self.sessions.write().await.insert(
            key.clone(),
            Arc::new(TmuxSession {
                name: name.to_owned(),
                generation,
                clients: Mutex::new(Vec::new()),
                in_copy_mode: AtomicBool::new(false),
            }),
        );
    }

    pub async fn has_session(&self, name: &str) -> bool {
        self.run(["has-session", "-t", name]).await.is_ok()
    }

    /// The `@armadra-runtime` server option, if a server is running and stamped.
    async fn server_owner(&self) -> Option<String> {
        self.run(["show-options", "-s", "-v", "-q", "@armadra-runtime"])
            .await
            .ok()
            .map(|value| value.trim().to_owned())
            .filter(|value| !value.is_empty())
    }

    /// Claim the server for this runtime if nobody has yet. Called after every
    /// `new-session`, which is the call that starts the server lazily.
    async fn stamp_server(&self) {
        if self.server_owner().await.is_none() {
            let _ = self
                .run([
                    "set-option",
                    "-s",
                    "@armadra-runtime",
                    &runtime_fingerprint(),
                ])
                .await;
        }
    }

    /// Startup check on a server that was already running.
    ///
    /// A server started by another runtime build (a development binary next to
    /// the packaged one, both on the same data directory) carries that
    /// runtime's environment and, on macOS, its sandbox — every session created
    /// under it would inherit both. An empty foreign server is therefore
    /// replaced; one that still has sessions is kept, because those sessions
    /// are the user's, and the mismatch is logged instead.
    pub async fn adopt_server(&self) {
        let Some(owner) = self.server_owner().await else {
            // No server, or an unstamped one from before this check existed.
            // The next `new-session` stamps it.
            return;
        };
        let ours = runtime_fingerprint();
        if owner == ours {
            return;
        }
        let sessions = self.list_alive().await.unwrap_or_default();
        if sessions.is_empty() {
            tracing::info!(owner, "replacing the empty tmux server of another runtime");
            let _ = self.run(["kill-server"]).await;
        } else {
            tracing::warn!(
                owner,
                sessions = sessions.len(),
                "the tmux server was started by another runtime; keeping its sessions"
            );
        }
    }

    pub async fn pane_pid(&self, key: &SessionKey) -> Option<i64> {
        let session = self.session(key).await.ok()?;
        let output = self
            .run([
                "display",
                "-p",
                "-t",
                &session.name,
                "#{pane_pid} #{pane_current_command}",
            ])
            .await
            .ok()?;
        output
            .split_whitespace()
            .next()
            .and_then(|pid| pid.parse::<i64>().ok())
    }

    async fn send_keys_bytes(&self, name: &str, bytes: &[u8]) -> AppResult<()> {
        // `-H` takes hex, so arbitrary control bytes survive intact — no
        // quoting rules, no shell, no key-name parsing.
        let mut arguments = vec![
            "send-keys".to_owned(),
            "-t".to_owned(),
            name.to_owned(),
            "-H".to_owned(),
        ];
        arguments.extend(bytes.iter().map(|byte| format!("{byte:02x}")));
        self.run(arguments).await.map(|_| ())
    }
}

#[async_trait]
impl TerminalBackend for TmuxBackend {
    fn kind(&self) -> BackendKind {
        BackendKind::Tmux
    }

    async fn create(&self, spec: TerminalSpec) -> AppResult<TerminalHandle> {
        ensure_conf(&self.conf)?;
        let name = session_name(&spec.workspace_id, &spec.session_key, spec.generation);
        // A leftover session under the same name would silently be reused.
        let _ = self.run(["kill-session", "-t", &name]).await;

        let mut arguments = vec![
            "new-session".to_owned(),
            "-d".to_owned(),
            "-s".to_owned(),
            name.clone(),
            "-x".to_owned(),
            spec.size.cols.max(2).to_string(),
            "-y".to_owned(),
            spec.size.rows.max(2).to_string(),
            "-c".to_owned(),
            spec.cwd.clone(),
        ];
        for (key, value) in &spec.env {
            arguments.push("-e".to_owned());
            arguments.push(format!("{key}={value}"));
        }
        arguments.push("--".to_owned());
        arguments.push(spec.executable());
        arguments.extend(spec.args.iter().cloned());
        self.run(arguments).await?;
        self.stamp_server().await;

        self.sessions.write().await.insert(
            spec.session_key.clone(),
            Arc::new(TmuxSession {
                name,
                generation: spec.generation,
                clients: Mutex::new(Vec::new()),
                in_copy_mode: AtomicBool::new(false),
            }),
        );
        let pid = self.pane_pid(&spec.session_key).await;
        Ok(TerminalHandle {
            session_key: spec.session_key.clone(),
            generation: spec.generation,
            backend_ref: Some(session_name(
                &spec.workspace_id,
                &spec.session_key,
                spec.generation,
            )),
            pid,
        })
    }

    /// One `tmux attach-session` client per socket, inside a PTY the runtime
    /// owns. The client redraws the pane by itself, which is why the tmux
    /// backend sends no `snapshot` frame.
    async fn attach(
        &self,
        key: &SessionKey,
        generation: u64,
        size: PtySize,
    ) -> AppResult<AttachHandle> {
        let session = self.session(key).await?;
        if session.generation != generation {
            return Err(AppError::Conflict(format!(
                "Terminal generation {generation} is stale; the session is at {}",
                session.generation
            )));
        }
        if !self.has_session(&session.name).await {
            return Err(AppError::NotFound("Terminal session has exited".into()));
        }

        let pair = native_pty_system()
            .openpty(PtySize {
                rows: size.rows.max(2),
                cols: size.cols.max(2),
                pixel_width: 0,
                pixel_height: 0,
            })
            .map_err(|error| AppError::Internal(format!("Could not create PTY: {error}")))?;
        let mut command = CommandBuilder::new("tmux");
        for argument in self.base_args() {
            command.arg(argument);
        }
        command.arg("attach-session");
        command.arg("-t");
        command.arg(&session.name);
        command.env_clear();
        for (name, value) in child_environment() {
            command.env(name, value);
        }
        let child = pair
            .slave
            .spawn_command(command)
            .map_err(|error| AppError::Internal(format!("Could not attach to tmux: {error}")))?;
        drop(pair.slave);
        let reader = pair
            .master
            .try_clone_reader()
            .map_err(|error| AppError::Internal(format!("Could not read PTY: {error}")))?;
        let writer = pair
            .master
            .take_writer()
            .map_err(|error| AppError::Internal(format!("Could not write PTY: {error}")))?;

        let (output, receiver) = broadcast::channel(512);
        // A second cursor over the same stream; the returned one keeps every
        // byte, including the ones consumed by the readiness wait below.
        let mut ready = output.subscribe();
        let (input, input_receiver) = mpsc::channel::<Bytes>(256);
        let id = self.next_client_id.fetch_add(1, Ordering::SeqCst);
        let client = Arc::new(TmuxClient {
            id,
            master: Mutex::new(Some(pair.master)),
            child: Mutex::new(Some(child)),
            input: input.clone(),
        });
        if let Ok(mut clients) = session.clients.lock() {
            clients.push(client.clone());
        }

        spawn_input_pump(format!("tmux-{id}"), writer, input_receiver);
        let backend = self.clone();
        let name = session.name.clone();
        let eof_key = key.clone();
        let eof_generation = session.generation;
        spawn_output_pump(
            OutputPump {
                name: format!("tmux-{id}"),
                output,
                replay: None,
                notices: self.notices.clone(),
                key: key.clone(),
                generation: session.generation,
            },
            reader,
            move || {
                // The client is gone. Either we detached it, or the session it
                // was showing ended — only the second case is an exit.
                let alive = std::process::Command::new("tmux")
                    .args(backend.base_args())
                    .args(["has-session", "-t", &name])
                    .stdin(Stdio::null())
                    .stdout(Stdio::null())
                    .stderr(Stdio::null())
                    .status()
                    .map(|status| status.success())
                    .unwrap_or(false);
                if !alive {
                    let _ = backend.notices.send(BackendNotice::Exited {
                        session_key: eof_key,
                        generation: eof_generation,
                        exit_code: None,
                    });
                }
            },
        );

        // tmux puts the client PTY into raw mode with TCSAFLUSH, which throws
        // away anything written before that point. Waiting for the client's
        // first redraw means the first keystroke of a caller that writes
        // immediately after attaching is not silently swallowed.
        let _ = tokio::time::timeout(std::time::Duration::from_millis(2000), ready.recv()).await;

        let detach_session = session.clone();
        let detach_client = client.clone();
        Ok(AttachHandle {
            output: receiver,
            input,
            generation: session.generation,
            detach: DetachGuard::new(move || {
                detach_client.detach();
                if let Ok(mut clients) = detach_session.clients.lock() {
                    clients.retain(|entry| entry.id != detach_client.id);
                }
            }),
        })
    }

    async fn write(&self, key: &SessionKey, bytes: &[u8]) -> AppResult<()> {
        let session = self.session(key).await?;
        // Typing always wins over scrollback: if we scrolled the pane back,
        // drop out of copy-mode first so the bytes reach the application.
        self.leave_copy_mode(&session).await;
        let client = session
            .clients
            .lock()
            .ok()
            .and_then(|clients| clients.last().cloned());
        match client {
            Some(client) => client
                .input
                .send(Bytes::copy_from_slice(bytes))
                .await
                .map_err(|_| AppError::NotFound("Terminal session is not running".into())),
            // Nothing is attached: hand the bytes to the pane directly.
            None => self.send_keys_bytes(&session.name, bytes).await,
        }
    }

    /// `window-size latest` makes the pane follow whichever client last moved,
    /// so resizing the client PTYs is all that is needed.
    async fn resize(&self, key: &SessionKey, size: PtySize) -> AppResult<()> {
        let session = self.session(key).await?;
        let clients = session
            .clients
            .lock()
            .map(|clients| clients.clone())
            .unwrap_or_default();
        let size = PtySize {
            rows: size.rows.max(2),
            cols: size.cols.max(2),
            pixel_width: 0,
            pixel_height: 0,
        };
        for client in clients {
            if let Ok(master) = client.master.lock()
                && let Some(master) = master.as_ref()
            {
                let _ = master.resize(size);
            }
        }
        Ok(())
    }

    async fn capture(&self, key: &SessionKey, lines: u32, with_escapes: bool) -> AppResult<String> {
        let session = self.session(key).await?;
        let start = if lines == 0 {
            "-".to_owned()
        } else {
            format!("-{lines}")
        };
        let mut arguments = vec!["capture-pane".to_owned(), "-p".to_owned(), "-J".to_owned()];
        if with_escapes {
            arguments.push("-e".to_owned());
        }
        arguments.extend([
            "-t".to_owned(),
            session.name.clone(),
            "-S".to_owned(),
            start,
        ]);
        let raw = self.run(arguments).await?;
        let text = if with_escapes {
            raw
        } else {
            strip_escapes(&raw)
        };
        Ok(tail_lines(&trim_captured(&text), lines))
    }

    /// A tmux buffer, not keystrokes: `-p` wraps it in the bracketed-paste
    /// sequence, `-d` deletes the buffer afterwards.
    async fn paste(&self, key: &SessionKey, text: &str, press_enter: bool) -> AppResult<()> {
        let session = self.session(key).await?;
        self.leave_copy_mode(&session).await;
        let buffer = format!("armadra-{}", uuid::Uuid::now_v7().simple());
        let file = std::env::temp_dir().join(format!("{buffer}.txt"));
        std::fs::write(&file, sanitize_paste(text).as_bytes())?;
        paths::harden_file(&file);
        let result = async {
            self.run([
                "load-buffer",
                "-b",
                &buffer,
                file.to_string_lossy().as_ref(),
            ])
            .await?;
            self.run([
                "paste-buffer",
                "-p",
                "-d",
                "-b",
                &buffer,
                "-t",
                &session.name,
            ])
            .await?;
            if press_enter {
                self.run(["send-keys", "-t", &session.name, "Enter"])
                    .await?;
            }
            Ok::<(), AppError>(())
        }
        .await;
        let _ = std::fs::remove_file(&file);
        if result.is_err() {
            let _ = self.run(["delete-buffer", "-b", &buffer]).await;
        }
        result
    }

    /// Wheel bridge (plan §18.5). The client is not in mouse mode, so tmux
    /// never sees the wheel; the web side sends whole lines here instead.
    ///
    /// `copy-mode -e` is the "exit when you scroll back to the bottom" variant,
    /// which is exactly the behaviour a wheel should have. `#{pane_in_mode}` is
    /// re-read afterwards because that automatic exit is the one transition we
    /// do not initiate ourselves.
    async fn scroll(&self, key: &SessionKey, lines: i32) -> AppResult<()> {
        if lines == 0 {
            return Ok(());
        }
        let session = self.session(key).await?;
        if !self.pane_in_mode(&session.name).await {
            // Entering copy-mode to scroll *down* would just bounce straight
            // back out; there is nothing below the live screen.
            if lines < 0 {
                session.in_copy_mode.store(false, Ordering::SeqCst);
                return Ok(());
            }
            self.run(["copy-mode", "-e", "-t", &session.name]).await?;
        }
        let count = lines.unsigned_abs().min(10_000).to_string();
        let command = if lines > 0 {
            "scroll-up"
        } else {
            "scroll-down"
        };
        self.run([
            "send-keys",
            "-X",
            "-N",
            &count,
            "-t",
            &session.name,
            command,
        ])
        .await?;
        // `-e` drops out on its own once the view is back at the bottom.
        let still = self.pane_in_mode(&session.name).await;
        session.in_copy_mode.store(still, Ordering::SeqCst);
        Ok(())
    }

    async fn foreground(&self, key: &SessionKey) -> AppResult<ForegroundInfo> {
        let session = self.session(key).await?;
        let output = self
            .run([
                "display",
                "-p",
                "-t",
                &session.name,
                "#{pane_pid} #{pane_current_command}",
            ])
            .await?;
        let mut parts = output.trim().splitn(2, ' ');
        let pid = parts.next().and_then(|pid| pid.parse::<i64>().ok());
        let command = parts.next().map(str::to_owned).filter(|it| !it.is_empty());
        Ok(ForegroundInfo {
            pid,
            command,
            children: pid.map(child_commands).unwrap_or_default(),
        })
    }

    async fn interrupt(&self, key: &SessionKey) -> AppResult<()> {
        let session = self.session(key).await?;
        self.run(["send-keys", "-t", &session.name, "C-c"])
            .await
            .map(|_| ())
    }

    async fn terminate_process(&self, key: &SessionKey) -> AppResult<()> {
        if let Some(pid) = self.pane_pid(key).await {
            terminate_tree(pid).await;
        }
        Ok(())
    }

    async fn destroy(&self, key: &SessionKey) -> AppResult<()> {
        let session = self.session(key).await?;
        if let Ok(clients) = session.clients.lock() {
            for client in clients.iter() {
                client.detach();
            }
        }
        let _ = self.run(["kill-session", "-t", &session.name]).await;
        self.sessions.write().await.remove(key);
        Ok(())
    }

    async fn list_alive(&self) -> AppResult<Vec<BackendRef>> {
        let output = match self
            .run([
                "list-sessions",
                "-F",
                "#{session_name} #{session_attached} #{session_activity}",
            ])
            .await
        {
            Ok(output) => output,
            // "no server running on ..." is the empty case, not a failure.
            Err(_) => return Ok(Vec::new()),
        };
        Ok(output
            .lines()
            .filter_map(|line| {
                let mut parts = line.split_whitespace();
                let name = parts.next()?.to_owned();
                if !name.starts_with(SESSION_PREFIX) {
                    return None;
                }
                Some(BackendRef {
                    name,
                    attached: parts.next().is_some_and(|value| value != "0"),
                })
            })
            .collect())
    }

    /// Destroys any `armadra-*` session the caller does not know about.
    async fn destroy_by_reference(&self, reference: &str) -> AppResult<()> {
        self.run(["kill-session", "-t", reference])
            .await
            .map(|_| ())
    }

    /// Runtime shutdown: drop the clients, keep the sessions. That is the whole
    /// reason tmux is the primary backend.
    async fn detach_all(&self) {
        let sessions: Vec<Arc<TmuxSession>> =
            self.sessions.read().await.values().cloned().collect();
        for session in sessions {
            let clients = session
                .clients
                .lock()
                .map(|clients| clients.clone())
                .unwrap_or_default();
            for client in clients {
                client.detach();
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn versions_compare_against_the_floor() {
        assert_eq!(parse_version("3.2a"), Some((3, 2)));
        assert_eq!(parse_version("3.7b"), Some((3, 7)));
        assert_eq!(parse_version("tmux 2.8"), Some((2, 8)));
        assert_eq!(parse_version("3"), Some((3, 0)));
        assert_eq!(parse_version("master"), None);
        assert!(parse_version("3.2a").unwrap() >= MINIMUM_VERSION);
        assert!(parse_version("2.8").unwrap() < MINIMUM_VERSION);
    }

    #[test]
    fn the_configuration_is_written_once_and_then_left_alone() {
        let directory = tempfile::tempdir().unwrap();
        let conf = directory.path().join("tmux.conf");
        ensure_conf(&conf).unwrap();
        let written = std::fs::metadata(&conf).unwrap().modified().unwrap();
        assert!(
            std::fs::read_to_string(&conf)
                .unwrap()
                .contains("prefix None")
        );

        std::thread::sleep(std::time::Duration::from_millis(20));
        ensure_conf(&conf).unwrap();
        assert_eq!(
            std::fs::metadata(&conf).unwrap().modified().unwrap(),
            written
        );

        // A conf from an older build is replaced, not merged.
        std::fs::write(&conf, "set -g status on\n").unwrap();
        ensure_conf(&conf).unwrap();
        assert_eq!(std::fs::read_to_string(&conf).unwrap(), rendered_conf());

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&conf).unwrap().permissions().mode();
            assert_eq!(mode & 0o777, 0o600);
            let directory_mode = std::fs::metadata(directory.path())
                .unwrap()
                .permissions()
                .mode();
            assert_eq!(directory_mode & 0o777, 0o700);
        }
    }

    /// Plan §18.3: true colour and the "resize to the smallest *attached*
    /// client, not the smallest that ever attached" rule both live in the conf.
    #[test]
    fn the_configuration_carries_the_compatibility_options() {
        let conf = rendered_conf();
        assert!(conf.contains("set -ga terminal-overrides \",*:Tc\""));
        assert!(conf.contains("set -ga terminal-features \",xterm-256color:RGB\""));
        assert!(conf.contains("set -g aggressive-resize on"));
        assert!(conf.contains("set -g window-size latest"));
        assert!(!conf.contains("{terminal}"));
    }

    /// Plan §18.3 amendment: the client must never be put into mouse mode,
    /// focus-reporting mode or the alternate screen, or xterm loses native
    /// selection and starts typing `\e[<0;8;3M` into whatever is running.
    #[test]
    fn the_client_keeps_selection_scrollback_and_the_clipboard() {
        let conf = rendered_conf();
        assert!(conf.contains("set -g mouse off"));
        assert!(conf.contains("set -g focus-events off"));
        assert!(!conf.contains("set -g mouse on"));
        assert!(!conf.contains("set -g focus-events on"));
        // No alternate screen for the client -> tmux history lands in xterm's.
        assert!(conf.contains("set -ga terminal-overrides \",*:smcup@:rmcup@\""));
        // OSC 52 from an inner app has to reach the outer terminal.
        assert!(conf.contains("set -g set-clipboard on"));
        assert!(conf.contains("set -as terminal-features \",xterm*:clipboard\""));
        assert!(conf.contains("set -g allow-passthrough on"));
    }

    /// The probed entry is one of the two we know how to render, never a
    /// placeholder and never an entry `infocmp` could not find.
    #[test]
    fn the_default_terminal_is_probed_and_falls_back() {
        let terminal = default_terminal();
        assert!(matches!(terminal, "tmux-256color" | "screen-256color"));
        assert!(rendered_conf().contains(&format!("set -g default-terminal \"{terminal}\"")));
    }
}
