/**
 * Every route the core owes the front end, and which phase writes it.
 *
 * The list is the Rust Runtime's 163 (`lib.rs` 148 on the main surface,
 * `hook/mod.rs` 15 on the hook surface), and it is contractual until R7
 * (contract §5.1). It is a table rather than 163 registrations so three things
 * can be true at once:
 *
 *   * a path this build has not written yet answers **501 with the feature's
 *     name**, not 404 — the front end can tell "not yet" from "wrong URL";
 *   * `tools/route-parity.mjs` can diff this table against the Rust source and
 *     fail the build when either side drifts;
 *   * each phase knows exactly which paths it is claiming, which is how R1–R5
 *     run in parallel without colliding.
 *
 * Path parameters are spelled in the camelCase the rest of the core uses;
 * `route-parity` maps them back to the Rust `snake_case` when it compares.
 */
export type RouteSurface = "runtime" | "hook";

export interface RouteEntry {
  /** `/api/workspaces/{workspaceId}` — one leading slash, no trailing one. */
  readonly path: string;
  readonly methods: readonly string[];
  /**
   * `runtime` is the main listener; `hook` is the separate loopback service
   * with its own credentials and body limit, which R3 brings up.
   */
  readonly surface: RouteSurface;
  /** What a person would call this, for the 501 message. */
  readonly feature?: string;
  /** Which phase writes it. */
  readonly phase?: number;
  /** Answered for real by this build. */
  readonly implemented?: true;
}

export const ROUTES: readonly RouteEntry[] = [
  {
    path: "/api/workspaces/{workspaceId}/nodes/{nodeId}/context-usage",
    methods: ["GET"],
    surface: "runtime",
    feature: "Agent 上下文用量",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/hunks",
    methods: ["GET", "POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/message/providers",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/message/source",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/message/generate",
    methods: ["POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repositories",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/log",
    methods: ["POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/refs",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/identity",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/branches",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/history",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/reflog",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/status-batch",
    methods: ["POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/worktree-binding",
    methods: ["POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/commit",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/commit-file",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/worktrees",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/rebase-todo",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/tags",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/remotes",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/stashes",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/integration",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/cherry-pick-preview",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/stash-detail",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/operations",
    methods: ["GET", "POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/operations/{operationId}",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/repository/operations/{operationId}/cancel",
    methods: ["POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/open-directory",
    methods: ["POST"],
    surface: "runtime",
    feature: "工作空间",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/workspaces/remote",
    methods: ["POST"],
    surface: "runtime",
    feature: "工作空间",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/execution-host",
    methods: ["PATCH"],
    surface: "runtime",
    feature: "工作空间",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/workspaces/import",
    methods: ["POST"],
    surface: "runtime",
    feature: "画布导入",
    phase: 4,
  },
  {
    path: "/api/ownership",
    methods: ["GET"],
    surface: "runtime",
    feature: "写入所有权记录",
    phase: 1,
  },
  {
    path: "/api/ownership/domains",
    methods: ["GET"],
    surface: "runtime",
    feature: "写入所有权记录",
    phase: 1,
  },
  { path: "/health", methods: ["GET"], surface: "runtime", implemented: true },
  {
    path: "/api/health",
    methods: ["GET"],
    surface: "runtime",
    implemented: true,
  },
  {
    path: "/api/workspaces",
    methods: ["GET", "POST"],
    surface: "runtime",
    feature: "工作空间",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}",
    methods: ["PATCH", "DELETE"],
    surface: "runtime",
    feature: "工作空间",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/open",
    methods: ["POST"],
    surface: "runtime",
    feature: "工作空间",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/boards",
    methods: ["GET", "POST"],
    surface: "runtime",
    feature: "画布",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/boards/{boardId}",
    methods: ["PATCH", "DELETE"],
    surface: "runtime",
    feature: "画布",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/boards/{boardId}/document",
    methods: ["GET", "PUT"],
    surface: "runtime",
    feature: "画布",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/files",
    methods: ["GET"],
    surface: "runtime",
    feature: "文件系统",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/file-info",
    methods: ["GET"],
    surface: "runtime",
    feature: "文件系统",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/file-download",
    methods: ["GET"],
    surface: "runtime",
    feature: "文件系统",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/imports",
    methods: ["POST"],
    surface: "runtime",
    feature: "画布导入",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/imports/local",
    methods: ["POST"],
    surface: "runtime",
    feature: "画布导入",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/file",
    methods: ["GET", "PUT"],
    surface: "runtime",
    feature: "文件系统",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/file-watch",
    methods: ["POST", "DELETE"],
    surface: "runtime",
    feature: "文件系统",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/file-version",
    methods: ["GET"],
    surface: "runtime",
    feature: "文件系统",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/file-index",
    methods: ["GET"],
    surface: "runtime",
    feature: "文件系统",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/file-search",
    methods: ["POST"],
    surface: "runtime",
    feature: "文件系统",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/file-entries",
    methods: ["POST"],
    surface: "runtime",
    feature: "文件系统",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/file-entries/rename",
    methods: ["POST"],
    surface: "runtime",
    feature: "文件系统",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/file-entries/trash",
    methods: ["GET", "POST"],
    surface: "runtime",
    feature: "文件系统",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/file-entries/restore",
    methods: ["POST"],
    surface: "runtime",
    feature: "文件系统",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/language-service",
    methods: ["GET"],
    surface: "runtime",
    feature: "语言服务",
    phase: 5,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/language/sessions",
    methods: ["POST"],
    surface: "runtime",
    feature: "语言服务",
    phase: 5,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/language/sessions/{sessionId}",
    methods: ["DELETE"],
    surface: "runtime",
    feature: "语言服务",
    phase: 5,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/language/sessions/{sessionId}/stream",
    methods: ["GET"],
    surface: "runtime",
    feature: "语言服务",
    phase: 5,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/language/sessions/{sessionId}/edits",
    methods: ["POST"],
    surface: "runtime",
    feature: "语言服务",
    phase: 5,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/language/servers/{serverId}/restart",
    methods: ["POST"],
    surface: "runtime",
    feature: "语言服务",
    phase: 5,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/language/servers/{serverId}/stop",
    methods: ["POST"],
    surface: "runtime",
    feature: "语言服务",
    phase: 5,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/status",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/init",
    methods: ["POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/diff",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/stage",
    methods: ["POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/unstage",
    methods: ["POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/revert",
    methods: ["POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/resolve",
    methods: ["POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/head-commit",
    methods: ["GET"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/git/commit",
    methods: ["POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/sessions",
    methods: ["GET"],
    surface: "runtime",
    feature: "终端会话",
    phase: 2,
  },
  {
    path: "/api/workspaces/{workspaceId}/events",
    methods: ["GET"],
    surface: "runtime",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/deliveries",
    methods: ["GET"],
    surface: "runtime",
    feature: "Agent 投递",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/resources",
    methods: ["GET"],
    surface: "runtime",
    feature: "资源采样",
    phase: 5,
  },
  {
    path: "/api/workspaces/{workspaceId}/resources/subscription",
    methods: ["POST"],
    surface: "runtime",
    feature: "资源采样",
    phase: 5,
  },
  {
    path: "/api/workspaces/{workspaceId}/resources/subscription/{subscriptionId}",
    methods: ["DELETE"],
    surface: "runtime",
    feature: "资源采样",
    phase: 5,
  },
  {
    path: "/api/workspaces/{workspaceId}/resources/orphans/{sessionId}/adopt",
    methods: ["POST"],
    surface: "runtime",
    feature: "资源采样",
    phase: 5,
  },
  {
    path: "/api/workspaces/{workspaceId}/resources/orphans/{orphanId}/terminate",
    methods: ["POST"],
    surface: "runtime",
    feature: "资源采样",
    phase: 5,
  },
  {
    path: "/api/power",
    methods: ["GET"],
    surface: "runtime",
    feature: "电源租约",
    phase: 5,
  },
  {
    path: "/api/power/leases",
    methods: ["POST"],
    surface: "runtime",
    feature: "电源租约",
    phase: 5,
  },
  {
    path: "/api/power/leases/{leaseId}",
    methods: ["DELETE"],
    surface: "runtime",
    feature: "电源租约",
    phase: 5,
  },
  {
    path: "/api/power/leases/{leaseId}/renew",
    methods: ["POST"],
    surface: "runtime",
    feature: "电源租约",
    phase: 5,
  },
  {
    path: "/api/control/confirm/{requestId}",
    methods: ["POST"],
    surface: "runtime",
    feature: "画布控制确认",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/handoffs",
    methods: ["POST", "GET"],
    surface: "runtime",
    feature: "Agent 交接",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/handoffs/{handoffId}",
    methods: ["GET"],
    surface: "runtime",
    feature: "Agent 交接",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/handoffs/{handoffId}/accept",
    methods: ["POST"],
    surface: "runtime",
    feature: "Agent 交接",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/handoffs/{handoffId}/cancel",
    methods: ["POST"],
    surface: "runtime",
    feature: "Agent 交接",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/context-links/{nodeId}",
    methods: ["PUT"],
    surface: "runtime",
    feature: "协作上下文链接",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/exports/{exportId}/png",
    methods: ["POST"],
    surface: "runtime",
    feature: "画布导出",
    phase: 4,
  },
  {
    path: "/api/workspaces/{workspaceId}/assets",
    methods: ["POST"],
    surface: "runtime",
    feature: "画布资产",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/assets/import",
    methods: ["POST"],
    surface: "runtime",
    feature: "画布资产",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/workspaces/{workspaceId}/assets/{assetId}",
    methods: ["GET"],
    surface: "runtime",
    feature: "画布资产",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/git/clone",
    methods: ["POST"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/git/clone/{jobId}",
    methods: ["GET", "DELETE"],
    surface: "runtime",
    feature: "Git 工具",
    phase: 4,
  },
  {
    path: "/api/terminals",
    methods: ["POST"],
    surface: "runtime",
    feature: "终端会话",
    phase: 2,
  },
  {
    path: "/api/terminals/backend",
    methods: ["GET"],
    surface: "runtime",
    feature: "终端会话",
    phase: 2,
  },
  {
    path: "/api/terminals/{sessionId}",
    methods: ["GET"],
    surface: "runtime",
    feature: "终端会话",
    phase: 2,
  },
  {
    path: "/api/terminals/{sessionId}/capture",
    methods: ["GET"],
    surface: "runtime",
    feature: "终端会话",
    phase: 2,
  },
  {
    path: "/api/terminals/{sessionId}/paste",
    methods: ["POST"],
    surface: "runtime",
    feature: "终端会话",
    phase: 2,
  },
  {
    path: "/api/terminals/{sessionId}/scroll",
    methods: ["POST"],
    surface: "runtime",
    feature: "终端会话",
    phase: 2,
  },
  {
    path: "/api/terminals/{sessionId}/terminate",
    methods: ["POST"],
    surface: "runtime",
    feature: "终端会话",
    phase: 2,
  },
  {
    path: "/api/terminals/{sessionId}/recycle",
    methods: ["POST"],
    surface: "runtime",
    feature: "终端会话",
    phase: 2,
  },
  {
    path: "/api/terminals/{sessionId}/ws",
    methods: ["GET"],
    surface: "runtime",
    feature: "终端会话",
    phase: 2,
  },
  {
    path: "/api/ssh/hosts/{hostId}/test",
    methods: ["POST"],
    surface: "runtime",
    feature: "SSH 执行主机",
    phase: 2,
    implemented: true,
  },
  {
    path: "/api/ssh/hosts/{hostId}/worker/test",
    methods: ["POST"],
    surface: "runtime",
    feature: "SSH 执行主机",
    phase: 2,
    implemented: true,
  },
  {
    path: "/api/ssh/hosts/{hostId}/host-keys/scan",
    methods: ["POST"],
    surface: "runtime",
    feature: "SSH 执行主机",
    phase: 2,
    implemented: true,
  },
  {
    path: "/api/ssh/hosts/{hostId}/host-keys",
    methods: ["POST", "DELETE"],
    surface: "runtime",
    feature: "SSH 执行主机",
    phase: 2,
    implemented: true,
  },
  {
    path: "/api/ssh/prompts",
    methods: ["GET"],
    surface: "runtime",
    feature: "SSH 执行主机",
    phase: 2,
    implemented: true,
  },
  {
    path: "/api/ssh/hosts/{hostId}/prompts/{promptId}",
    methods: ["POST", "DELETE"],
    surface: "runtime",
    feature: "SSH 执行主机",
    phase: 2,
    implemented: true,
  },
  {
    path: "/api/ssh/askpass/prompts",
    methods: ["POST"],
    surface: "runtime",
    feature: "SSH 执行主机",
    phase: 5,
  },
  {
    path: "/api/ssh/askpass/prompts/{promptId}",
    methods: ["GET"],
    surface: "runtime",
    feature: "SSH 执行主机",
    phase: 5,
  },
  {
    path: "/api/conversations",
    methods: ["GET"],
    surface: "runtime",
    feature: "会话记录索引",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/conversations/refresh",
    methods: ["POST"],
    surface: "runtime",
    feature: "会话记录索引",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/agents",
    methods: ["GET"],
    surface: "runtime",
    feature: "Agent 目录",
    phase: 1,
  },
  {
    path: "/api/models/catalog",
    methods: ["GET"],
    surface: "runtime",
    feature: "模型目录",
    phase: 1,
  },
  {
    path: "/api/models/catalog/refresh",
    methods: ["POST"],
    surface: "runtime",
    feature: "模型目录",
    phase: 1,
  },
  {
    path: "/api/agents/{agentId}/models",
    methods: ["GET"],
    surface: "runtime",
    feature: "Agent 目录",
    phase: 1,
  },
  {
    path: "/api/agents/{agentId}/integration",
    methods: ["GET"],
    surface: "runtime",
    feature: "Agent 接入安装",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/agents/{agentId}/integration/install",
    methods: ["POST"],
    surface: "runtime",
    feature: "Agent 接入安装",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/agents/{agentId}/integration/uninstall",
    methods: ["POST"],
    surface: "runtime",
    feature: "Agent 接入安装",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/agents/{agentId}/integration/repair",
    methods: ["POST"],
    surface: "runtime",
    feature: "Agent 接入安装",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/agent-status/{nodeId}/read",
    methods: ["POST"],
    surface: "runtime",
    feature: "Agent 状态",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/agent-status/{nodeId}/suggest-title",
    methods: ["POST"],
    surface: "runtime",
    feature: "Agent 状态",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/agent-status/{nodeId}/transcript",
    methods: ["GET"],
    surface: "runtime",
    feature: "Agent 状态",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/terminals/{sessionId}/node-token/refresh",
    methods: ["POST"],
    surface: "runtime",
    feature: "Agent 节点凭据",
    phase: 3,
    implemented: true,
  },
  {
    path: "/api/settings",
    methods: ["GET", "PATCH"],
    surface: "runtime",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/settings/local",
    methods: ["GET"],
    surface: "runtime",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/execution-hosts",
    methods: ["GET"],
    surface: "runtime",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/execution-hosts/export",
    methods: ["GET"],
    surface: "runtime",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/execution-hosts/import",
    methods: ["POST"],
    surface: "runtime",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/execution-hosts/{hostId}",
    methods: ["PUT", "DELETE"],
    surface: "runtime",
    phase: 1,
    implemented: true,
  },
  {
    path: "/api/execution-hosts/{hostId}/validate",
    methods: ["POST"],
    surface: "runtime",
    feature: "执行主机配置",
    phase: 2,
    implemented: true,
  },
  {
    path: "/api/data/info",
    methods: ["GET"],
    surface: "runtime",
    feature: "数据与备份",
    phase: 1,
  },
  {
    path: "/api/data/backup",
    methods: ["POST"],
    surface: "runtime",
    feature: "数据与备份",
    phase: 1,
  },
  {
    path: "/api/data/legacy-kanban-archives",
    methods: ["GET"],
    surface: "runtime",
    feature: "数据与备份",
    phase: 1,
  },
  {
    path: "/api/data/legacy-kanban-archives/{canvasId}",
    methods: ["GET"],
    surface: "runtime",
    feature: "数据与备份",
    phase: 1,
  },
  {
    path: "/api/data/legacy-kanban-archives/{canvasId}/export",
    methods: ["GET"],
    surface: "runtime",
    feature: "数据与备份",
    phase: 1,
  },
  {
    path: "/api/usage",
    methods: ["GET"],
    surface: "runtime",
    feature: "用量统计",
    phase: 5,
  },
  {
    path: "/api/usage/refresh",
    methods: ["POST"],
    surface: "runtime",
    feature: "用量统计",
    phase: 5,
  },
  {
    path: "/api/usage/mini",
    methods: ["GET"],
    surface: "runtime",
    phase: 5,
    implemented: true,
  },
  {
    path: "/api/usage/cost",
    methods: ["GET"],
    surface: "runtime",
    feature: "用量统计",
    phase: 5,
  },
  {
    path: "/api/usage/cost/refresh",
    methods: ["POST"],
    surface: "runtime",
    feature: "用量统计",
    phase: 5,
  },
  {
    path: "/api/usage/copilot",
    methods: ["GET"],
    surface: "runtime",
    feature: "用量统计",
    phase: 5,
  },
  {
    path: "/api/usage/copilot/login",
    methods: ["POST"],
    surface: "runtime",
    feature: "用量统计",
    phase: 5,
  },
  {
    path: "/api/usage/copilot/poll",
    methods: ["POST"],
    surface: "runtime",
    feature: "用量统计",
    phase: 5,
  },
  {
    path: "/api/usage/copilot/logout",
    methods: ["POST"],
    surface: "runtime",
    feature: "用量统计",
    phase: 5,
  },
  {
    path: "/api/approvals/{pendingId}/answer",
    methods: ["POST"],
    surface: "runtime",
    feature: "Agent 审批",
    phase: 3,
    implemented: true,
  },
  {
    path: "/verify",
    methods: ["GET"],
    surface: "hook",
    feature: "Hook 凭据校验",
    phase: 3,
    implemented: true,
  },
  {
    path: "/hook/{agentId}",
    methods: ["POST"],
    surface: "hook",
    feature: "Hook 事件接收",
    phase: 3,
    implemented: true,
  },
  {
    path: "/context-link/{verb}",
    methods: ["POST"],
    surface: "hook",
    feature: "协作上下文链接",
    phase: 3,
  },
  {
    path: "/control/{verb}",
    methods: ["POST"],
    surface: "hook",
    feature: "画布控制动词",
    phase: 3,
  },
  {
    path: "/browser/{verb}",
    methods: ["POST"],
    surface: "hook",
    feature: "浏览器动词",
    phase: 5,
    implemented: true,
  },
  {
    path: "/automation/agent-target",
    methods: ["POST"],
    surface: "hook",
    feature: "Agent 调度接口",
    phase: 3,
  },
  {
    path: "/automation/agent-prompt",
    methods: ["POST"],
    surface: "hook",
    feature: "Agent 调度接口",
    phase: 3,
  },
  {
    path: "/automation/agent-prompt/lookup",
    methods: ["POST"],
    surface: "hook",
    feature: "Agent 调度接口",
    phase: 3,
  },
  {
    path: "/automation/session-start",
    methods: ["POST"],
    surface: "hook",
    feature: "会话调度接口",
    phase: 3,
  },
  {
    path: "/automation/session-signal",
    methods: ["POST"],
    surface: "hook",
    feature: "会话调度接口",
    phase: 3,
  },
  {
    path: "/automation/session-reclaim",
    methods: ["POST"],
    surface: "hook",
    feature: "会话调度接口",
    phase: 3,
  },
  {
    path: "/automation/session-capture",
    methods: ["POST"],
    surface: "hook",
    feature: "会话调度接口",
    phase: 3,
  },
  {
    path: "/automation/session-title",
    methods: ["POST"],
    surface: "hook",
    feature: "会话调度接口",
    phase: 3,
  },
  {
    path: "/automation/session-context-usage",
    methods: ["POST"],
    surface: "hook",
    feature: "会话调度接口",
    phase: 3,
  },
  {
    path: "/automation/agent-approval",
    methods: ["POST"],
    surface: "hook",
    feature: "Agent 调度接口",
    phase: 3,
  },
];
