[package]
name = "armadra-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
prost = "=0.14.1"

[build-dependencies]
prost-build = "=0.14.1"
protoc-bin-vendored = "=3.2.0"

[dev-dependencies]
prost-build = "=0.14.1"
protoc-bin-vendored = "=3.2.0"
