//! The TS extension Pi and Oh My Pi load in-process — 协作通道 §3.5.
//!
//! Pi and OMP have no command hooks at all; what they have is an extension API
//! (`pi.on(event, handler)`) that runs inside the CLI's own process. So instead
//! of forking `armadra-hook` per event, the generated module speaks the same
//! HTTP to the same `hook.sock` from inside the CLI — channel B of §3.1, which
//! is the in-process form of the command Hook and *not* a more trusted one:
//!
//!   * the same `hook-endpoint.env` bearer and the same `node-tokens/<id>`,
//!     re-read on every event because a terminal outlives the runtime that
//!     spawned it;
//!   * the same `terminalBinding` with a `sourceRevision` taken from the same
//!     `context-sequences/<session>-<generation>.seq` counter;
//!   * the same `POST /hook/<agent>` body, so the runtime cannot tell the two
//!     apart and therefore cannot give either one extra authority.
//!
//! When the socket cannot be reached the module falls back to spawning
//! `armadra-hook <agent>` with the payload on stdin — the path the opencode
//! plugin uses today, kept so a stripped-down environment still reports.
//!
//! The generator is split so B3 can reuse it: [`transport_prelude`] is the
//! provider-agnostic half (endpoint, token, sequence, transport, the two
//! `armadraReport*` entry points) and [`pi_extension_source`] is the Pi/OMP
//! wiring on top of it. An opencode plugin needs the first and its own second.

use std::path::Path;

use super::HOOK_CLIENT_REVISION;

/// Handlers that also push a `ctx.getContextUsage()` reading. Pi's own
/// documentation calls `agent_settled` the event a status integration should
/// use, and the compaction/model events are the two moments an existing
/// reading stops describing the session.
pub const PI_CONTEXT_EVENTS: &[&str] = &[
    "agent_end",
    "agent_settled",
    "session_compact",
    "model_select",
];

/// Oh My Pi 18.x settles through `session_stop` rather than `agent_settled`
/// and compacts through `auto_compaction_end`; both are added to Pi's list.
pub const OMP_CONTEXT_EVENTS: &[&str] = &[
    "agent_end",
    "agent_settled",
    "session_stop",
    "session_compact",
    "auto_compaction_end",
    "model_select",
];

/// Escapes a value for a double-quoted JavaScript string literal. Windows
/// paths are the reason this exists at all.
pub fn js_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    for character in value.chars() {
        match character {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\u{2028}' => out.push_str("\\u2028"),
            '\u{2029}' => out.push_str("\\u2029"),
            character if (character as u32) < 0x20 || character as u32 == 0x7f => {
                out.push_str(&format!("\\u{:04x}", character as u32));
            }
            character => out.push(character),
        }
    }
    out
}

fn js_string_array(values: &[&str]) -> String {
    let items = values
        .iter()
        .map(|value| format!("\"{}\"", js_string(value)))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{items}]")
}

/// The provider-agnostic half of the module: constants, endpoint reading,
/// sequence allocation, both transports, and the two entry points
/// `armadraReport(payload)` and `armadraReportContextUsage(ctx)`.
///
/// `context_events` may be empty for a provider with no live window to read;
/// `armadraReportContextUsage` is then simply never called.
pub fn transport_prelude(agent_id: &str, client_bin: &Path, context_events: &[&str]) -> String {
    format!(
        "{PRELUDE_HEADER}\nconst ARMADRA_CLIENT = \"{client}\";\nconst ARMADRA_AGENT = \"{agent}\";\nconst ARMADRA_CLIENT_REVISION = \"{HOOK_CLIENT_REVISION}\";\nconst ARMADRA_CONTEXT_EVENTS = {context};\n{PRELUDE_BODY}",
        client = js_string(&client_bin.to_string_lossy()),
        agent = js_string(agent_id),
        context = js_string_array(context_events),
    )
}

/// The whole Pi / Oh My Pi extension: the prelude plus the `pi.on` wiring for
/// `events`. Deterministic — reinstalling writes the same bytes.
pub fn pi_extension_source(
    agent_id: &str,
    client_bin: &Path,
    events: &[&str],
    context_events: &[&str],
) -> String {
    format!(
        "{prelude}\nconst ARMADRA_EVENTS = {events};\n{PI_WIRING}",
        prelude = transport_prelude(agent_id, client_bin, context_events),
        events = js_string_array(events),
    )
}

const PRELUDE_HEADER: &str = r##"// Armadra — agent status reporter.
// Generated by the runtime's hook installer; edits are overwritten on reinstall.
//
// Reports what this CLI is doing to the local Armadra runtime over the same
// unix socket, headers and body the `armadra-hook` binary uses. Outside a
// canvas terminal ARMADRA_NODE_ID is unset, nothing is registered, and this
// file is inert.
//
// It never blocks a turn, never blocks a tool call, never changes a message and
// never injects context. Every path is wrapped: a canvas problem must not
// become a CLI problem."##;

const PRELUDE_BODY: &str = r##"
import { spawn } from "node:child_process";
import * as fs from "node:fs";
import * as http from "node:http";
import * as path from "node:path";

const ARMADRA_TIMEOUT_MS = 1500;
const ARMADRA_MAX_TEXT = 2000;
const ARMADRA_MAX_PATH = 4096;
const ARMADRA_U64_MASK = 0xffffffffffffffffn;

function armadraEnv(name) {
  const value = process.env[name];
  return typeof value === "string" && value.trim() !== "" ? value : undefined;
}

// The same gate as `crates/hook/src/endpoint.rs::is_valid_node_id`: an id only
// becomes part of a filesystem path after it passes this.
function armadraIsValidId(value) {
  return (
    typeof value === "string" &&
    value.length > 0 &&
    value.length <= 80 &&
    /^[A-Za-z0-9_-]+$/.test(value)
  );
}

// The runtime caps its own short strings at 200 characters and rejects control
// characters; a value that would be dropped there is not worth sending.
function armadraText(value) {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim();
  if (trimmed === "" || trimmed.length > 200) return undefined;
  return /[\u0000-\u001f\u007f]/.test(trimmed) ? undefined : trimmed;
}

// `KEY='value'` with POSIX single-quote escaping, mirroring
// `crates/hook/src/endpoint.rs::parse_endpoint_file`.
function armadraUnquote(value) {
  if (value.length >= 2 && value.startsWith("'") && value.endsWith("'")) {
    return value.slice(1, -1).split("'\\''").join("'");
  }
  if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
    return value.slice(1, -1).split('\\"').join('"').split("\\\\").join("\\");
  }
  return value;
}

function armadraParseEndpoint(text) {
  const map = new Map();
  for (const rawLine of text.split("\n")) {
    let line = rawLine.trim();
    if (line === "" || line.startsWith("#")) continue;
    if (line.startsWith("export ")) line = line.slice(7).trim();
    const separator = line.indexOf("=");
    if (separator <= 0) continue;
    const key = line.slice(0, separator).trim();
    if (key === "") continue;
    map.set(key, armadraUnquote(line.slice(separator + 1).trim()));
  }
  return map;
}

// Read on every event, never cached: the terminal can outlive the runtime that
// spawned it, and the next runtime writes a new socket path and a new bearer.
function armadraSession() {
  const nodeId = armadraEnv("ARMADRA_NODE_ID");
  const endpointFile = armadraEnv("ARMADRA_ENDPOINT_FILE");
  if (!nodeId || !endpointFile) return undefined;
  let text;
  try {
    text = fs.readFileSync(endpointFile, "utf8");
  } catch {
    return undefined;
  }
  const map = armadraParseEndpoint(text);
  const sock = map.get("ARMADRA_HOOK_SOCK") || undefined;
  const rawPort = map.get("ARMADRA_HOOK_PORT") ?? "";
  const port = /^\d{1,5}$/.test(rawPort) ? Number(rawPort) : 0;
  const usablePort = port > 0 && port < 65536 ? port : undefined;
  if (!sock && usablePort === undefined) return undefined;
  return {
    nodeId,
    endpointFile,
    sock,
    port: usablePort,
    hookToken: map.get("ARMADRA_HOOK_TOKEN") || "",
    tokenDir: map.get("ARMADRA_NODE_TOKEN_DIR") || undefined,
  };
}

function armadraHeaders(session) {
  const headers = {
    "X-Armadra-Hook-Client": ARMADRA_CLIENT_REVISION,
    "X-Armadra-Hook-Token": session.hookToken,
  };
  if (session.tokenDir && armadraIsValidId(session.nodeId)) {
    try {
      const token = fs.readFileSync(path.join(session.tokenDir, session.nodeId), "utf8").trim();
      if (token !== "") headers["X-Armadra-Node-Token"] = token;
    } catch {
      // A missing node token downgrades the report; it does not cancel it.
    }
  }
  return headers;
}

// The `terminalBinding.sourceRevision` counter, byte for byte the format of
// `crates/hook/src/context_usage.rs::next_revision`: 8 big-endian bytes
// followed by their bitwise inverse, incremented in place.
//
// The Rust client holds an advisory lock across the read-modify-write and
// neither node nor bun can take one. It is still safe, because of the
// direction the counter is read in: `terminal/observation.rs` only believes an
// idle report whose revision is *strictly greater* than the last input fence,
// so a lost update — two writers landing on the same value — can only make a
// report look older than it is and be dropped. It can never make a stale
// report outrank a newer input fence. Within one CLI process this whole
// sequence is synchronous, so two handlers cannot interleave inside it.
function armadraNextRevision(session) {
  const sessionId = armadraEnv("ARMADRA_SESSION_ID");
  const rawGeneration = armadraEnv("ARMADRA_SESSION_GENERATION") ?? "";
  if (!armadraIsValidId(sessionId) || !/^\d{1,16}$/.test(rawGeneration)) return undefined;
  const generation = Number(rawGeneration);
  if (!Number.isSafeInteger(generation)) return undefined;
  const directory = path.join(path.dirname(session.endpointFile), "context-sequences");
  try {
    const stats = fs.lstatSync(directory);
    if (!stats.isDirectory()) return undefined;
    if (process.platform !== "win32" && (stats.mode & 0o077) !== 0) return undefined;
  } catch {
    return undefined;
  }
  const file = path.join(directory, sessionId + "-" + generation + ".seq");
  try {
    if (!fs.lstatSync(file).isFile()) return undefined;
  } catch {
    return undefined;
  }
  let handle;
  try {
    handle = fs.openSync(file, "r+");
  } catch {
    return undefined;
  }
  try {
    const bytes = Buffer.alloc(16);
    if (fs.readSync(handle, bytes, 0, 16, 0) !== 16) return undefined;
    const count = bytes.readBigUInt64BE(0);
    // A corrupt counter is never reset to zero: a delayed old report must not
    // be able to look new again after a crash.
    if ((count ^ ARMADRA_U64_MASK) !== bytes.readBigUInt64BE(8)) return undefined;
    const next = count + 1n;
    if (next > ARMADRA_U64_MASK) return undefined;
    const out = Buffer.alloc(16);
    out.writeBigUInt64BE(next, 0);
    out.writeBigUInt64BE(next ^ ARMADRA_U64_MASK, 8);
    fs.writeSync(handle, out, 0, 16, 0);
    fs.fsyncSync(handle);
    return { sessionId, generation, sourceRevision: next.toString() };
  } catch {
    return undefined;
  } finally {
    try {
      fs.closeSync(handle);
    } catch {
      // Nothing left to do with a handle that will not close.
    }
  }
}

// bun's documented unix transport. Tried first only when bun is the runtime;
// node's `fetch` has no `unix` option and would dial the network instead.
async function armadraBunPost(session, pathname, headers, body) {
  if (typeof Bun === "undefined" || typeof fetch !== "function") return undefined;
  try {
    const response = await fetch("http://localhost" + pathname, {
      unix: session.sock,
      method: "POST",
      headers: { ...headers, "Content-Type": "application/json", Connection: "close" },
      body,
      signal: AbortSignal.timeout(ARMADRA_TIMEOUT_MS),
    });
    try {
      await response.arrayBuffer();
    } catch {
      // The status is all we wanted; an undrained body is not a failure.
    }
    return response.status;
  } catch {
    return undefined;
  }
}

function armadraNodePost(options, headers, body) {
  return new Promise(resolve => {
    let settled = false;
    const finish = value => {
      if (settled) return;
      settled = true;
      resolve(value);
    };
    let request;
    try {
      request = http.request(
        {
          ...options,
          method: "POST",
          agent: false,
          timeout: ARMADRA_TIMEOUT_MS,
          headers: {
            ...headers,
            "Content-Type": "application/json",
            "Content-Length": Buffer.byteLength(body),
            Connection: "close",
          },
        },
        response => {
          response.resume();
          response.on("end", () => finish(response.statusCode));
          response.on("error", () => finish(undefined));
        },
      );
    } catch {
      finish(undefined);
      return;
    }
    const abort = () => {
      try {
        request.destroy();
      } catch {
        // Already gone.
      }
      finish(undefined);
    };
    request.on("error", () => finish(undefined));
    request.on("timeout", abort);
    const timer = setTimeout(abort, ARMADRA_TIMEOUT_MS);
    if (typeof timer.unref === "function") timer.unref();
    try {
      request.end(body);
    } catch {
      abort();
    }
  });
}

async function armadraPost(session, pathname, body) {
  const headers = armadraHeaders(session);
  if (session.sock) {
    const bunStatus = await armadraBunPost(session, pathname, headers, body);
    if (bunStatus !== undefined) return bunStatus;
    const status = await armadraNodePost(
      { socketPath: session.sock, path: pathname },
      headers,
      body,
    );
    if (status !== undefined) return status;
  }
  if (session.port !== undefined) {
    return await armadraNodePost(
      { host: "127.0.0.1", port: session.port, path: pathname },
      headers,
      body,
    );
  }
  return undefined;
}

// The pre-direct-connect path, kept as the fallback: `armadra-hook <agent>`
// reads the provider payload on stdin and builds the envelope itself.
function armadraSpawn(payloadText) {
  return new Promise(resolve => {
    let child;
    try {
      child = spawn(ARMADRA_CLIENT, [ARMADRA_AGENT], { stdio: ["pipe", "ignore", "ignore"] });
    } catch {
      resolve();
      return;
    }
    let settled = false;
    const finish = () => {
      if (settled) return;
      settled = true;
      resolve();
    };
    child.on("error", finish);
    child.on("close", finish);
    const timer = setTimeout(() => {
      try {
        child.kill();
      } catch {
        // Already gone.
      }
      finish();
    }, ARMADRA_TIMEOUT_MS);
    if (typeof timer.unref === "function") timer.unref();
    try {
      child.stdin.on("error", () => {});
      child.stdin.end(payloadText);
    } catch {
      finish();
    }
  });
}

/** Report one provider payload. Never throws and never rejects. */
async function armadraReport(payload) {
  let payloadText;
  try {
    payloadText = JSON.stringify(payload);
  } catch {
    return;
  }
  const session = armadraSession();
  if (session) {
    const body = { nodeId: session.nodeId, version: 1, payload };
    const binding = armadraNextRevision(session);
    if (binding) body.terminalBinding = binding;
    let bodyText;
    try {
      bodyText = JSON.stringify(body);
    } catch {
      return;
    }
    const status = await armadraPost(session, "/hook/" + ARMADRA_AGENT, bodyText);
    if (status !== undefined) return;
  }
  await armadraSpawn(payloadText);
}

// `ctx.getContextUsage()` gives one already-summed number, so it lands in the
// first of the runtime's three disjoint buckets and the other two are zero;
// the runtime adds them and gets exactly that number back. A null `tokens` —
// what the CLI reports between a compaction and the next response — is
// forwarded as a null `current_usage`, which is what tells the runtime the
// previous reading no longer describes this session.
function armadraContextData(ctx) {
  const providerSession = armadraText(ctx?.sessionManager?.getSessionId?.());
  const modelId = armadraText(ctx?.model?.id);
  if (!providerSession || !modelId) return undefined;
  let usage;
  try {
    usage = ctx?.getContextUsage?.();
  } catch {
    return undefined;
  }
  const capacity =
    usage && Number.isSafeInteger(usage.contextWindow) && usage.contextWindow > 0
      ? usage.contextWindow
      : null;
  const window = { context_window_size: capacity };
  if (usage) {
    const tokens = usage.tokens;
    window.current_usage =
      Number.isSafeInteger(tokens) && tokens >= 0
        ? { input_tokens: tokens, cache_creation_input_tokens: 0, cache_read_input_tokens: 0 }
        : null;
  }
  return { session_id: providerSession, model: { id: modelId }, context_window: window };
}

/** Report the live context window. Never throws and never rejects. */
async function armadraReportContextUsage(ctx) {
  const session = armadraSession();
  if (!session) return;
  const data = armadraContextData(ctx);
  if (!data) return;
  const binding = armadraNextRevision(session);
  if (!binding) return;
  let bodyText;
  try {
    bodyText = JSON.stringify({
      nodeId: session.nodeId,
      version: 1,
      payload: { armadraContextUsage: { ...binding, data } },
    });
  } catch {
    return;
  }
  await armadraPost(session, "/hook/" + ARMADRA_AGENT, bodyText);
}
"##;

const PI_WIRING: &str = r##"
function armadraPayload(name, event, ctx) {
  const payload = { hookEventName: name, provider: ARMADRA_AGENT };
  const sessionId =
    armadraText(ctx?.sessionManager?.getSessionId?.()) ?? armadraText(event?.session_id);
  if (sessionId) payload.sessionId = sessionId;
  const file = ctx?.sessionManager?.getSessionFile?.() ?? event?.session_file;
  if (typeof file === "string" && file !== "" && file.length <= ARMADRA_MAX_PATH) {
    payload.transcriptPath = file;
  }
  if (typeof ctx?.cwd === "string" && ctx.cwd !== "" && ctx.cwd.length <= ARMADRA_MAX_PATH) {
    payload.cwd = ctx.cwd;
  }
  const toolName = armadraText(event?.toolName);
  if (toolName) payload.toolName = toolName;
  if (name === "before_agent_start" && typeof event?.prompt === "string") {
    payload.prompt = event.prompt.slice(0, ARMADRA_MAX_TEXT);
  }
  if (name === "model_select") {
    const modelId = armadraText(event?.model?.id);
    if (modelId) payload.modelId = modelId;
  }
  return payload;
}

async function armadraHandle(name, event, ctx) {
  try {
    if (ARMADRA_CONTEXT_EVENTS.includes(name)) {
      await armadraReportContextUsage(ctx);
    }
    await armadraReport(armadraPayload(name, event, ctx));
  } catch {
    // Reporting is best effort; a handler that threw would reach the CLI.
  }
}

export default function (pi) {
  // Outside a canvas terminal nothing is registered at all.
  if (!armadraEnv("ARMADRA_NODE_ID")) return;
  for (const name of ARMADRA_EVENTS) {
    try {
      pi.on(name, (event, ctx) => {
        // Shutdown is awaited: the process is on its way out and an unawaited
        // report would be lost. Everything else is fire-and-forget, so a slow
        // socket can never add latency to a turn.
        const reported = armadraHandle(name, event, ctx);
        if (name === "session_shutdown") return reported;
        reported.catch(() => {});
        return undefined;
      });
    } catch {
      // An event this build of the CLI has never heard of is not an error.
    }
  }
}
"##;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hook::install::is_managed_command;

    fn client() -> &'static Path {
        Path::new("/opt/armadra/armadra-hook")
    }

    #[test]
    fn a_windows_path_survives_as_one_javascript_literal() {
        let source = transport_prelude(
            "pi",
            Path::new(r"C:\Program Files\armadra\armadra-hook.exe"),
            PI_CONTEXT_EVENTS,
        );
        assert!(source.contains(r"C:\\Program Files\\armadra\\armadra-hook.exe"));
        assert_eq!(source.matches("const ARMADRA_CLIENT = \"").count(), 1);
        // And the marker the uninstaller recognises survives the escaping.
        assert!(is_managed_command(&source));
    }

    #[test]
    fn control_characters_never_reach_the_literal() {
        assert_eq!(js_string("a\nb"), "a\\u000ab");
        assert_eq!(js_string("a\u{7f}b"), "a\\u007fb");
        assert_eq!(js_string("a\u{2028}b"), "a\\u2028b");
        assert_eq!(js_string("plain"), "plain");
    }

    #[test]
    fn the_generated_module_carries_the_contract_it_has_to_keep() {
        let source = pi_extension_source(
            "pi",
            client(),
            crate::hook::install::PI_HOOK_EVENTS,
            PI_CONTEXT_EVENTS,
        );
        // Gate, credentials and binding — the three things §3.5 requires.
        assert!(source.contains("armadraEnv(\"ARMADRA_NODE_ID\")"));
        assert!(source.contains("X-Armadra-Hook-Token"));
        assert!(source.contains("X-Armadra-Node-Token"));
        assert!(source.contains("terminalBinding"));
        assert!(source.contains("context-sequences"));
        // Both transports plus the fallback.
        assert!(source.contains("unix: session.sock"));
        assert!(source.contains("socketPath: session.sock"));
        assert!(source.contains("spawn(ARMADRA_CLIENT, [ARMADRA_AGENT]"));
        // The route is the provider's own.
        assert!(source.contains("const ARMADRA_AGENT = \"pi\";"));
        // Every subscribed event is wired.
        for event in crate::hook::install::PI_HOOK_EVENTS {
            assert!(source.contains(&format!("\"{event}\"")), "{event}");
        }
        // A blocking decision is never returned to the CLI (§3.5: observe,
        // never block), so no handler may resolve to one.
        assert!(!source.contains("block:"));
        assert!(!source.contains("permissionDecision"));
    }

    #[test]
    fn rendering_is_deterministic_and_provider_specific() {
        let first = pi_extension_source("pi", client(), &["agent_end"], PI_CONTEXT_EVENTS);
        let again = pi_extension_source("pi", client(), &["agent_end"], PI_CONTEXT_EVENTS);
        assert_eq!(first, again, "reinstall must write the same bytes");

        let omp = pi_extension_source("omp", client(), &["agent_end"], OMP_CONTEXT_EVENTS);
        assert_ne!(first, omp);
        assert!(omp.contains("const ARMADRA_AGENT = \"omp\";"));
        assert!(omp.contains("\"session_stop\""));
        assert!(!first.contains("\"session_stop\""));
    }

    #[test]
    fn an_empty_context_list_still_renders() {
        let source = transport_prelude("opencode", client(), &[]);
        assert!(source.contains("const ARMADRA_CONTEXT_EVENTS = [];"));
        // The prelude is standalone: it must not mention the Pi-only wiring.
        assert!(!source.contains("export default function"));
        assert!(source.contains("async function armadraReport("));
    }
}
