//! opencode — a plugin file, because opencode has no hook configuration.
//!
//! opencode exposes one `event` bus to plugins and nothing resembling the
//! per-event command hooks the other three CLIs have. So the "installer" writes
//! a small ESM module into `<config home>/plugins/` and the "uninstaller"
//! deletes it; there is no shared file to merge into and therefore nothing of
//! the user's to preserve — except other plugins, which live in their own files.
//!
//! The plugin is gated on `ARMADRA_NODE_ID`: in a terminal the user opened
//! themselves the variable is absent, the handler returns immediately, and
//! opencode behaves exactly as if the plugin were not there.

use std::{fs, path::Path};

use super::{HOOK_CLIENT_REVISION, InstallReport, is_managed_command};
use crate::error::AppResult;

const AGENT_ID: &str = "opencode";
const PLUGIN_FILE: &str = "armadra-status.js";

pub fn plugin_path(config_home: &Path) -> std::path::PathBuf {
    config_home.join("plugins").join(PLUGIN_FILE)
}

pub fn install(config_home: &Path, client_bin: &Path) -> AppResult<InstallReport> {
    let path = plugin_path(config_home);
    super::write_atomically(&path, plugin_source(client_bin).as_bytes())?;
    Ok(InstallReport {
        agent_id: AGENT_ID.to_owned(),
        config_path: path.to_string_lossy().into_owned(),
        client_bin: Some(client_bin.to_string_lossy().into_owned()),
        client_revision: HOOK_CLIENT_REVISION,
        installed: true,
        warning: None,
    })
}

pub fn uninstall(config_home: &Path) -> AppResult<InstallReport> {
    let path = plugin_path(config_home);
    // Only delete a file that is recognisably ours — the name could have been
    // taken over by something else the user wrote.
    if let Ok(existing) = fs::read_to_string(&path)
        && is_managed_command(&existing)
    {
        fs::remove_file(&path)?;
    }
    Ok(InstallReport {
        agent_id: AGENT_ID.to_owned(),
        config_path: path.to_string_lossy().into_owned(),
        client_bin: None,
        client_revision: HOOK_CLIENT_REVISION,
        installed: false,
        warning: None,
    })
}

/// The plugin body. `Bun.spawn` is the reliable way to hand a process something
/// on stdin under the runtime opencode ships with; `$` is kept in the signature
/// (and used as the fallback) because that is the documented plugin shape.
fn plugin_source(client_bin: &Path) -> String {
    let binary = client_bin
        .to_string_lossy()
        .replace('\\', "\\\\")
        .replace('"', "\\\"");
    format!(
        r#"// Armadra — agent status reporter (revision {revision}).
// Generated by the runtime's hook installer; edits are overwritten on reinstall.
//
// Forwards opencode's event bus to the local canvas runtime. Outside a canvas
// terminal `ARMADRA_NODE_ID` is unset and every call returns immediately, so the
// plugin is inert in a terminal you opened yourself.

const ARMADRA_CLIENT = "{binary}";
const ARMADRA_AGENT = "{agent}";

export const ArmadraStatus = async ({{ $ }}) => ({{
  event: async ({{ event }}) => {{
    if (!process.env.ARMADRA_NODE_ID) return;
    let payload;
    try {{
      payload = JSON.stringify(event);
    }} catch {{
      return;
    }}
    try {{
      if (typeof Bun !== "undefined" && typeof Bun.spawn === "function") {{
        const child = Bun.spawn([ARMADRA_CLIENT, ARMADRA_AGENT], {{
          stdin: new TextEncoder().encode(payload),
          stdout: "ignore",
          stderr: "ignore",
        }});
        await child.exited;
        return;
      }}
      await $`${{ARMADRA_CLIENT}} ${{ARMADRA_AGENT}}`.quiet();
    }} catch {{
      // Reporting is best effort: a missing client must never break a turn.
    }}
  }},
}});
"#,
        revision = HOOK_CLIENT_REVISION,
        binary = binary,
        agent = AGENT_ID,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn client() -> &'static Path {
        Path::new("/opt/armadra/armadra-hook")
    }

    #[test]
    fn the_plugin_is_written_gated_and_idempotent() {
        let home = tempdir().unwrap();
        let report = install(home.path(), client()).unwrap();
        assert!(report.installed);
        let path = plugin_path(home.path());
        assert!(path.ends_with("plugins/armadra-status.js"));

        let source = fs::read_to_string(&path).unwrap();
        assert!(source.contains("export const ArmadraStatus"));
        assert!(source.contains("process.env.ARMADRA_NODE_ID"));
        assert!(source.contains("/opt/armadra/armadra-hook"));
        assert!(source.contains("\"opencode\""));
        assert!(is_managed_command(&source));

        install(home.path(), client()).unwrap();
        assert_eq!(source, fs::read_to_string(&path).unwrap());
    }

    #[test]
    fn uninstall_removes_our_plugin_and_leaves_a_stranger_alone() {
        let home = tempdir().unwrap();
        install(home.path(), client()).unwrap();
        uninstall(home.path()).unwrap();
        assert!(!plugin_path(home.path()).exists());
        // Uninstalling again is a no-op, not an error.
        assert!(uninstall(home.path()).is_ok());

        // Someone else's file under the same name is not ours to delete.
        let path = plugin_path(home.path());
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, "export const Other = () => ({});\n").unwrap();
        uninstall(home.path()).unwrap();
        assert!(path.exists());
    }

    #[test]
    fn a_windows_style_path_is_escaped_for_javascript() {
        let source = plugin_source(Path::new(r"C:\Program Files\armadra\armadra-hook.exe"));
        assert!(source.contains(r"C:\\Program Files\\armadra\\armadra-hook.exe"));
        // And the literal it lands in is still one well-formed string.
        assert_eq!(source.matches("const ARMADRA_CLIENT = \"").count(), 1);
    }
}
