/**
 * Extension -> MIME, the same answer `mime_guess` gives.
 *
 * `files::read_text_file` reports `mime_guess::from_path(..).first_or_text_plain()`
 * and `imports::file_info` reports `first_or_octet_stream()`, and both strings
 * reach the front end: the editor picks a highlighter from the first and the
 * file card picks a preview mode from the second. A plausible hand-written
 * table would answer `text/plain` where the Runtime answers
 * `video/vnd.dlna.mpeg-tts` for a `.ts` file, which is exactly the kind of
 * quiet divergence this port must not introduce.
 *
 * Carried over from `mime_guess` 2.0.5's `MIME_TYPES` (the first entry per
 * extension, which is what `first_or_*` returns), packed as `ext:mime|...` so
 * the table is a few dozen lines rather than a thousand. Extensions are
 * matched case-insensitively, as `mime_guess` matches them.
 */
const PACKED = [
  "123:application/vnd.lotus-1-2-3|323:text/h323|3dml:text/vnd.in3d.3dml|3ds:image/x-3ds|3g2:video/3gpp2|3gp:vi",
  "deo/3gpp|3gp2:video/3gpp2|3gpp:video/3gpp|7z:application/x-7z-compressed|aa:audio/audible|aab:application/x-",
  "authorware-bin|aac:audio/aac|aaf:application/octet-stream|aam:application/x-authorware-map|aas:application/x",
  "-authorware-seg|aax:audio/vnd.audible.aax|abw:application/x-abiword|ac:application/pkix-attr-cert|ac3:audio/",
  "ac3|aca:application/octet-stream|acc:application/vnd.americandynamics.acc|accda:application/msaccess.addin|a",
  "ccdb:application/msaccess|accdc:application/msaccess.cab|accde:application/msaccess|accdr:application/msacce",
  "ss.runtime|accdt:application/msaccess|accdw:application/msaccess.webapplication|accft:application/msaccess.f",
  "template|ace:application/x-ace-compressed|acu:application/vnd.acucobol|acutc:application/vnd.acucorp|acx:app",
  "lication/internet-property-stream|addin:text/xml|ade:application/msaccess|adobebridge:application/x-bridge-u",
  "rl|adp:application/msaccess|adt:audio/vnd.dlna.adts|adts:audio/aac|aep:application/vnd.audiograph|afm:applic",
  "ation/octet-stream|afp:application/vnd.ibm.modcap|ahead:application/vnd.ahead.space|ai:application/postscrip",
  "t|aif:audio/aiff|aifc:audio/aiff|aiff:audio/aiff|ait:application/vnd.dvb.ait|amc:application/mpeg|ami:applic",
  "ation/vnd.amiga.ami|anx:application/annodex|apk:application/vnd.android.package-archive|apng:image/apng|appc",
  "ache:text/cache-manifest|application:application/x-ms-application|apr:application/vnd.lotus-approach|arc:app",
  "lication/x-freearc|arj:application/x-arj|art:image/x-jg|arw:image/x-sony-arw|asa:application/xml|asax:applic",
  "ation/xml|asc:application/pgp-signature|ascx:application/xml|asd:application/octet-stream|asf:video/x-ms-asf",
  "|ashx:application/xml|asi:application/octet-stream|asm:text/plain|asmx:application/xml|aso:application/vnd.a",
  "ccpac.simply.aso|aspx:application/xml|asr:video/x-ms-asf|asx:video/x-ms-asf|atc:application/vnd.acucorp|atom",
  ":application/atom+xml|atomcat:application/atomcat+xml|atomsvc:application/atomsvc+xml|atx:application/vnd.an",
  "tix.game-component|au:audio/basic|avi:video/x-msvideo|avif:image/avif|avifs:image/avif-sequence|aw:applicati",
  "on/applixware|axa:audio/annodex|axs:application/olescript|axv:video/annodex|azf:application/vnd.airzip.files",
  "ecure.azf|azs:application/vnd.airzip.filesecure.azs|azw:application/vnd.amazon.ebook|bas:text/plain|bat:appl",
  "ication/x-msdownload|bcpio:application/x-bcpio|bdf:application/x-font-bdf|bdm:application/vnd.syncml.dm+wbxm",
  "l|bdoc:application/bdoc|bed:application/vnd.realvnc.bed|bh2:application/vnd.fujitsu.oasysprs|bin:application",
  "/octet-stream|blb:application/x-blorb|blorb:application/x-blorb|bmi:application/vnd.bmi|bmp:image/bmp|book:a",
  "pplication/vnd.framemaker|box:application/vnd.previewsystems.box|boz:application/x-bzip2|bpk:application/oct",
  "et-stream|btif:image/prs.btif|buffer:application/octet-stream|bz:application/x-bzip|bz2:application/x-bzip2|",
  "c:text/plain|c11amc:application/vnd.cluetrust.cartomobile-config|c4d:application/vnd.clonk.c4group|c4f:appli",
  "cation/vnd.clonk.c4group|c4g:application/vnd.clonk.c4group|c4p:application/vnd.clonk.c4group|c4u:application",
  "/vnd.clonk.c4group|cab:application/octet-stream|caf:audio/x-caf|calx:application/vnd.ms-office.calx|cap:appl",
  "ication/vnd.tcpdump.pcap|car:application/vnd.curl.car|cat:application/vnd.ms-pki.seccat|cb7:application/x-cb",
  "r|cba:application/x-cbr|cbr:application/x-cbr|cbt:application/x-cbr|cbz:application/x-cbr|cc:text/plain|cco:",
  "application/x-cocoa|cct:application/x-director|ccxml:application/ccxml+xml|cd:text/plain|cdbcmsg:application",
  "/vnd.contact.cmsg|cdda:audio/aiff|cdf:application/x-cdf|cdkey:application/vnd.mediastation.cdkey|cdmia:appli",
  "cation/cdmi-capability|cdmic:application/cdmi-container|cdmid:application/cdmi-domain|cdmio:application/cdmi",
  "-object|cdmiq:application/cdmi-queue|cdx:chemical/x-cdx|cdxml:application/vnd.chemdraw+xml|cdy:application/v",
  "nd.cinderella|cer:application/x-x509-ca-cert|cfg:text/plain|cfs:application/x-cfs-compressed|cgm:image/cgm|c",
  "hat:application/x-chat|chm:application/vnd.ms-htmlhelp|chrt:application/vnd.kde.kchart|cif:chemical/x-cif|ci",
  "l:application/vnd.ms-artgalry|cla:application/vnd.claymore|class:application/x-java-applet|clkk:application/",
  "vnd.crick.clicker.keyboard|clkp:application/vnd.crick.clicker.palette|clkt:application/vnd.crick.clicker.tem",
  "plate|clkw:application/vnd.crick.clicker.wordbank|clkx:application/vnd.crick.clicker|clp:application/x-mscli",
  "p|cmc:application/vnd.cosmocaller|cmd:text/plain|cmdf:chemical/x-cmdf|cml:chemical/x-cml|cmp:application/vnd",
  ".yellowriver-custom-menu|cmx:image/x-cmx|cnf:text/plain|cod:image/cis-cod|coffee:text/coffeescript|com:appli",
  "cation/x-msdownload|conf:text/plain|config:application/xml|contact:text/x-ms-contact|coverage:application/xm",
  "l|cpio:application/x-cpio|cpp:text/plain|cpt:application/mac-compactpro|cr2:image/x-canon-cr2|cr3:image/x-ca",
  "non-cr3|crd:application/x-mscardfile|crl:application/pkix-crl|crt:application/x-x509-ca-cert|crw:image/x-can",
  "on-crw|crx:application/x-chrome-extension|cryptonote:application/vnd.rig.cryptonote|cs:text/plain|csdproj:te",
  "xt/plain|csh:application/x-csh|csl:application/vnd.citationstyles.style+xml|csml:chemical/x-csml|csp:applica",
  "tion/vnd.commonspace|csproj:text/plain|css:text/css|cst:application/x-director|csv:text/csv|cu:application/c",
  "u-seeme|cur:application/octet-stream|curl:text/vnd.curl|cww:application/prs.cww|cxt:application/x-director|c",
  "xx:text/plain|dae:model/vnd.collada+xml|daf:application/vnd.mobius.daf|dart:application/vnd.dart|dat:applica",
  "tion/octet-stream|dataless:application/vnd.fdsn.seed|datasource:application/xml|davmount:application/davmoun",
  "t+xml|dbk:application/docbook+xml|dbproj:text/plain|dcr:application/x-director|dcurl:text/vnd.curl.dcurl|dd2",
  ":application/vnd.oma.dd2+xml|ddd:application/vnd.fujixerox.ddd|deb:application/octet-stream|def:text/plain|d",
  "eploy:application/octet-stream|der:application/x-x509-ca-cert|dfac:application/vnd.dreamfactory|dgc:applicat",
  "ion/x-dgc-compressed|dgml:application/xml|dib:image/bmp|dic:text/x-c|dif:video/x-dv|dir:application/x-direct",
  "or|dis:application/vnd.mobius.dis|disco:text/xml|dist:application/octet-stream|distz:application/octet-strea",
  "m|divx:video/divx|djv:image/vnd.djvu|djvu:image/vnd.djvu|dll:application/x-msdownload|dll.config:text/xml|dl",
  "m:text/dlm|dmg:application/octet-stream|dmp:application/vnd.tcpdump.pcap|dms:application/octet-stream|dna:ap",
  "plication/vnd.dna|dng:image/x-adobe-dng|doc:application/msword|dot:application/msword|dp:application/vnd.osg",
  "i.dp|dpg:application/vnd.dpgraph|dra:audio/vnd.dra|dsc:text/prs.lines.tag|dsp:application/octet-stream|dssc:",
  "application/dssc+der|dsw:text/plain|dtb:application/x-dtbook+xml|dtd:text/xml|dts:audio/vnd.dts|dtsconfig:te",
  "xt/xml|dtshd:audio/vnd.dts.hd|dump:application/octet-stream|dv:video/x-dv|dvb:video/vnd.dvb.file|dvi:applica",
  "tion/x-dvi|dwf:drawing/x-dwf|dwg:application/acad|dwp:application/octet-stream|dxf:application/x-dxf|dxp:app",
  "lication/vnd.spotfire.dxp|dxr:application/x-director|ear:application/java-archive|ecelp4800:audio/vnd.nuera.",
  "ecelp4800|ecelp7470:audio/vnd.nuera.ecelp7470|ecelp9600:audio/vnd.nuera.ecelp9600|ecma:text/javascript|edm:a",
  "pplication/vnd.novadigm.edm|edx:application/vnd.novadigm.edx|efif:application/vnd.picsel|ei6:application/vnd",
  ".pg.osasli|elc:application/octet-stream|emf:application/x-msmetafile|eml:message/rfc822|emma:application/emm",
  "a+xml|emz:application/octet-stream|eol:audio/vnd.digital-winds|eot:application/vnd.ms-fontobject|eps:applica",
  "tion/postscript|epub:application/epub+zip|erf:application/x-endace-erf|es:text/javascript|es3:application/vn",
  "d.eszigno3+xml|esa:application/vnd.osgi.subsystem|esf:application/vnd.epson.esf|et3:application/vnd.eszigno3",
  "+xml|etl:application/etl|etx:text/x-setext|eva:application/x-eva|evy:application/envoy|exe:application/octet",
  "-stream|exe.config:text/xml|exi:application/exi|ext:application/vnd.novadigm.ext|ez:application/andrew-inset",
  "|ez2:application/vnd.ezpix-album|ez3:application/vnd.ezpix-package|f:text/x-fortran|f4v:video/x-f4v|f77:text",
  "/x-fortran|f90:text/x-fortran|fbs:image/vnd.fastbidsheet|fcdt:application/vnd.adobe.formscentral.fcdt|fcs:ap",
  "plication/vnd.isac.fcs|fdf:application/vnd.fdf|fe_launch:application/vnd.denovo.fcselayout-link|feature:text",
  "/x-gherkin|fg5:application/vnd.fujitsu.oasysgp|fgd:application/x-director|fh:image/x-freehand|fh4:image/x-fr",
  "eehand|fh5:image/x-freehand|fh7:image/x-freehand|fhc:image/x-freehand|fif:application/fractals|fig:applicati",
  "on/x-xfig|filters:application/xml|fla:application/octet-stream|flac:audio/flac|fli:video/x-fli|flo:applicati",
  "on/vnd.micrografx.flo|flr:x-world/x-vrml|flv:video/x-flv|flw:application/vnd.kde.kivio|flx:text/vnd.fmi.flex",
  "stor|fly:text/vnd.fly|fm:application/vnd.framemaker|fnc:application/vnd.frogans.fnc|for:text/x-fortran|fpx:i",
  "mage/vnd.fpx|frame:application/vnd.framemaker|fsc:application/vnd.fsc.weblaunch|fsscript:application/fsharp-",
  "script|fst:image/vnd.fst|fsx:application/fsharp-script|ftc:application/vnd.fluxtime.clip|fvt:video/vnd.fvt|f",
  "xp:application/vnd.adobe.fxp|fxpl:application/vnd.adobe.fxp|fzs:application/vnd.fuzzysheet|g2w:application/v",
  "nd.geoplan|g3:image/g3fax|g3w:application/vnd.geospace|gac:application/vnd.groove-account|gam:application/x-",
  "tads|gbr:application/rpki-ghostbusters|gca:application/x-gca-compressed|gdl:model/vnd.gdl|gdoc:application/v",
  "nd.google-apps.document|gemini:text/gemini|generictest:application/xml|geo:application/vnd.dynageo|geojson:a",
  "pplication/geo+json|gex:application/vnd.geometry-explorer|ggb:application/vnd.geogebra.file|ggt:application/",
  "vnd.geogebra.tool|ghf:application/vnd.groove-help|gif:image/gif|gim:application/vnd.groove-identity-message|",
  "glb:model/gltf-binary|gltf:model/gltf+json|gmi:text/gemini|gml:application/gml+xml|gmx:application/vnd.gmx|g",
  "numeric:application/x-gnumeric|gph:application/vnd.flographit|gpx:application/gpx+xml|gqf:application/vnd.gr",
  "afeq|gqs:application/vnd.grafeq|gram:application/srgs|gramps:application/x-gramps-xml|gre:application/vnd.ge",
  "ometry-explorer|group:text/x-ms-group|grv:application/vnd.groove-injector|grxml:application/srgs+xml|gsf:app",
  "lication/x-font-ghostscript|gsheet:application/vnd.google-apps.spreadsheet|gslides:application/vnd.google-ap",
  "ps.presentation|gsm:audio/x-gsm|gtar:application/x-gtar|gtm:application/vnd.groove-tool-message|gtw:model/vn",
  "d.gtw|gv:text/vnd.graphviz|gxf:application/gxf|gxt:application/vnd.geonext|gz:application/gzip|h:text/plain|",
  "h261:video/h261|h263:video/h263|h264:video/h264|hal:application/vnd.hal+xml|hbci:application/vnd.hbci|hbs:te",
  "xt/x-handlebars-template|hdd:application/x-virtualbox-hdd|hdf:application/x-hdf|hdml:text/x-hdml|hdr:image/v",
  "nd.radiance|heic:image/heic|heics:image/heic-sequence|heif:image/heif|heifs:image/heif-sequence|hh:text/plai",
  "n|hhc:application/x-oleobject|hhk:application/octet-stream|hhp:application/octet-stream|hjson:application/hj",
  "son|hlp:application/winhlp|hpgl:application/vnd.hp-hpgl|hpid:application/vnd.hp-hpid|hpp:text/plain|hps:appl",
  "ication/vnd.hp-hps|hqx:application/mac-binhex40|hta:application/hta|htc:text/x-component|htke:application/vn",
  "d.kenameaapp|htm:text/html|html:text/html|htt:text/webviewhtml|hvd:application/vnd.yamaha.hv-dic|hvp:applica",
  "tion/vnd.yamaha.hv-voice|hvs:application/vnd.yamaha.hv-script|hxa:application/xml|hxc:application/xml|hxd:ap",
  "plication/octet-stream|hxe:application/xml|hxf:application/xml|hxh:application/octet-stream|hxi:application/",
  "octet-stream|hxk:application/xml|hxq:application/octet-stream|hxr:application/octet-stream|hxs:application/o",
  "ctet-stream|hxt:text/html|hxv:application/xml|hxw:application/octet-stream|hxx:text/plain|i:text/plain|i2g:a",
  "pplication/vnd.intergeo|icc:application/vnd.iccprofile|ice:x-conference/x-cooltalk|icm:application/vnd.iccpr",
  "ofile|ico:image/x-icon|ics:text/calendar|idl:text/plain|ief:image/ief|ifb:text/calendar|ifm:application/vnd.",
  "shana.informed.formdata|iges:model/iges|igl:application/vnd.igloader|igm:application/vnd.insors.igm|igs:mode",
  "l/iges|igx:application/vnd.micrografx.igx|iif:application/vnd.shana.informed.interchange|iii:application/x-i",
  "phone|img:application/octet-stream|imp:application/vnd.accpac.simply.imp|ims:application/vnd.ms-ims|in:text/",
  "plain|inc:text/plain|inf:application/octet-stream|ini:text/plain|ink:application/inkml+xml|inkml:application",
  "/inkml+xml|inl:text/plain|ins:application/x-internet-signup|install:application/x-install-instructions|iota:",
  "application/vnd.astraea-software.iota|ipa:application/x-itunes-ipa|ipfix:application/ipfix|ipg:application/x",
  "-itunes-ipg|ipk:application/vnd.shana.informed.package|ipproj:text/plain|ipsw:application/x-itunes-ipsw|iqy:",
  "text/x-ms-iqy|irm:application/vnd.ibm.rights-management|irp:application/vnd.irepository.package+xml|iso:appl",
  "ication/octet-stream|isp:application/x-internet-signup|ite:application/x-itunes-ite|itlp:application/x-itune",
  "s-itlp|itms:application/x-itunes-itms|itp:application/vnd.shana.informed.formtemplate|itpc:application/x-itu",
  "nes-itpc|ivf:video/x-ivf|ivp:application/vnd.immervision-ivp|ivu:application/vnd.immervision-ivu|jad:text/vn",
  "d.sun.j2me.app-descriptor|jade:text/jade|jam:application/vnd.jam|jar:application/java-archive|jardiff:applic",
  "ation/x-java-archive-diff|java:application/octet-stream|jck:application/liquidmotion|jcz:application/liquidm",
  "otion|jfif:image/jpeg|jisp:application/vnd.jisp|jlt:application/vnd.hp-jlyt|jng:image/x-jng|jnlp:application",
  "/x-java-jnlp-file|joda:application/vnd.joost.joda-archive|jp2:image/jp2|jpb:application/octet-stream|jpe:ima",
  "ge/jpeg|jpeg:image/jpeg|jpf:image/jpx|jpg:image/jpeg|jpg2:image/jp2|jpgm:video/jpm|jpgv:video/jpeg|jpm:image",
  "/jpm|jpx:image/jpx|js:text/javascript|jsm:text/javascript|json:application/json|json5:application/json5|json",
  "ld:application/ld+json|jsonml:application/jsonml+json|jsx:text/javascript|jsxbin:text/plain|jxl:image/jxl|k2",
  "5:image/x-kodak-k25|kar:audio/midi|karbon:application/vnd.kde.karbon|kdc:image/x-kodak-kdc|kfo:application/v",
  "nd.kde.kformula|kia:application/vnd.kidspiration|kml:application/vnd.google-earth.kml+xml|kmz:application/vn",
  "d.google-earth.kmz|kne:application/vnd.kinar|knp:application/vnd.kinar|kon:application/vnd.kde.kontour|kpr:a",
  "pplication/vnd.kde.kpresenter|kpt:application/vnd.kde.kpresenter|kpxx:application/vnd.ds-keypoint|ksp:applic",
  "ation/vnd.kde.kspread|ktr:application/vnd.kahootz|ktx:image/ktx|ktz:application/vnd.kahootz|kwd:application/",
  "vnd.kde.kword|kwt:application/vnd.kde.kword|lasxml:application/vnd.las.las+xml|latex:application/x-latex|les",
  ":application/vnd.hhe.lesson-player|less:text/less|lha:application/x-lzh-compressed|library-ms:application/wi",
  "ndows-library+xml|link66:application/vnd.route66.link66+xml|list:text/plain|list3820:application/vnd.ibm.mod",
  "cap|listafp:application/vnd.ibm.modcap|lit:application/x-ms-reader|litcoffee:text/coffeescript|lnk:applicati",
  "on/x-ms-shortcut|loadtest:application/xml|log:text/plain|lostxml:application/lost+xml|lpk:application/octet-",
  "stream|lrf:application/octet-stream|lrm:application/vnd.ms-lrm|lsf:video/x-la-asf|lst:text/plain|lsx:video/x",
  "-la-asf|ltf:application/vnd.frogans.ltf|lua:text/x-lua|luac:application/x-lua-bytecode|lvp:audio/vnd.lucent.",
  "voice|lwp:application/vnd.lotus-wordpro|lzh:application/octet-stream|m13:application/x-msmediaview|m14:appli",
  "cation/x-msmediaview|m1v:video/mpeg|m21:application/mp21|m2a:audio/mpeg|m2t:video/vnd.dlna.mpeg-tts|m2ts:vid",
  "eo/vnd.dlna.mpeg-tts|m2v:video/mpeg|m3a:audio/mpeg|m3u:audio/x-mpegurl|m3u8:audio/x-mpegurl|m4a:audio/m4a|m4",
  "b:audio/m4b|m4p:audio/m4p|m4r:audio/x-m4r|m4u:video/vnd.mpegurl|m4v:video/x-m4v|ma:application/mathematica|m",
  "ac:image/x-macpaint|mads:application/mads+xml|mag:application/vnd.ecowin.chart|mak:text/plain|maker:applicat",
  "ion/vnd.framemaker|man:application/x-troff-man|manifest:application/x-ms-manifest|map:text/plain|mar:applica",
  "tion/octet-stream|markdown:text/markdown|master:application/xml|mathml:application/mathml+xml|mb:application",
  "/mathematica|mbk:application/vnd.mobius.mbk|mbox:application/mbox|mc1:application/vnd.medcalcdata|mcd:applic",
  "ation/vnd.mcd|mcurl:text/vnd.curl.mcurl|md:text/markdown|mda:application/msaccess|mdb:application/x-msaccess",
  "|mde:application/msaccess|mdi:image/vnd.ms-modi|mdp:application/octet-stream|me:application/x-troff-me|mesh:",
  "model/mesh|meta4:application/metalink4+xml|metalink:application/metalink+xml|mets:application/mets+xml|mfm:a",
  "pplication/vnd.mfmp|mfp:application/x-shockwave-flash|mft:application/rpki-manifest|mgp:application/vnd.osge",
  "o.mapguide.package|mgz:application/vnd.proteus.magazine|mht:message/rfc822|mhtml:message/rfc822|mid:audio/mi",
  "d|midi:audio/mid|mie:application/x-mie|mif:application/vnd.mif|mime:message/rfc822|mix:application/octet-str",
  "eam|mj2:video/mj2|mjp2:video/mj2|mjs:application/javascript|mk:text/plain|mk3d:video/x-matroska|mka:audio/x-",
  "matroska|mkd:text/x-markdown|mks:video/x-matroska|mkv:video/x-matroska|mlp:application/vnd.dolby.mlp|mmd:app",
  "lication/vnd.chipnuts.karaoke-mmd|mmf:application/x-smaf|mml:text/mathml|mmr:image/vnd.fujixerox.edmics-mmr|",
  "mng:video/x-mng|mno:text/xml|mny:application/x-msmoney|mobi:application/x-mobipocket-ebook|mod:video/mpeg|mo",
  "ds:application/mods+xml|mov:video/quicktime|movie:video/x-sgi-movie|mp2:audio/mpeg|mp21:application/mp21|mp2",
  "a:audio/mpeg|mp2v:video/mpeg|mp3:audio/mpeg|mp4:video/mp4|mp4a:audio/mp4|mp4s:application/mp4|mp4v:video/mp4",
  "|mpa:video/mpeg|mpc:application/vnd.mophun.certificate|mpd:application/dash+xml|mpe:video/mpeg|mpeg:video/mp",
  "eg|mpf:application/vnd.ms-mediapackage|mpg:video/mpeg|mpg4:video/mp4|mpga:audio/mpeg|mpkg:application/vnd.ap",
  "ple.installer+xml|mpm:application/vnd.blueice.multipass|mpn:application/vnd.mophun.application|mpp:applicati",
  "on/vnd.ms-project|mpt:application/vnd.ms-project|mpv2:video/mpeg|mpy:application/vnd.ibm.minipay|mqv:video/q",
  "uicktime|mqy:application/vnd.mobius.mqy|mrc:application/marc|mrcx:application/marcxml+xml|mrw:image/x-minolt",
  "a-mrw|ms:application/x-troff-ms|mscml:application/mediaservercontrol+xml|mseed:application/vnd.fdsn.mseed|ms",
  "eq:application/vnd.mseq|msf:application/vnd.epson.msf|msg:application/vnd.ms-outlook|msh:model/mesh|msi:appl",
  "ication/octet-stream|msl:application/vnd.mobius.msl|msm:application/octet-stream|mso:application/octet-strea",
  "m|msp:application/octet-stream|msty:application/vnd.muvee.style|mts:video/vnd.dlna.mpeg-tts|mtx:application/",
  "xml|mus:application/vnd.musician|musicxml:application/vnd.recordare.musicxml+xml|mvb:application/x-msmediavi",
  "ew|mvc:application/x-miva-compiled|mwf:application/vnd.mfer|mxf:application/mxf|mxl:application/vnd.recordar",
  "e.musicxml|mxml:application/xv+xml|mxp:application/x-mmxp|mxs:application/vnd.triscape.mxs|mxu:video/vnd.mpe",
  "gurl|n-gage:application/vnd.nokia.n-gage.symbian.install|n3:text/n3|nb:application/mathematica|nbp:applicati",
  "on/vnd.wolfram.player|nc:application/x-netcdf|ncx:application/x-dtbncx+xml|nef:image/x-nikon-nef|nfo:text/x-",
  "nfo|ngdat:application/vnd.nokia.n-gage.data|nitf:application/vnd.nitf|nlu:application/vnd.neurolanguage.nlu|",
  "nml:application/vnd.enliven|nnd:application/vnd.noblenet-directory|nns:application/vnd.noblenet-sealer|nnw:a",
  "pplication/vnd.noblenet-web|npx:image/vnd.net-fpx|nq:application/n-quads|nrw:image/x-nikon-nrw|nsc:video/x-m",
  "s-asf|nsf:application/vnd.lotus-notes|nt:application/n-triples|ntf:application/vnd.nitf|nws:message/rfc822|n",
  "zb:application/x-nzb|oa2:application/vnd.fujitsu.oasys2|oa3:application/vnd.fujitsu.oasys3|oas:application/v",
  "nd.fujitsu.oasys|obd:application/x-msbinder|obj:application/x-tgif|ocx:application/octet-stream|oda:applicat",
  "ion/oda|odb:application/vnd.oasis.opendocument.database|odc:application/vnd.oasis.opendocument.chart|odf:app",
  "lication/vnd.oasis.opendocument.formula|odg:application/vnd.oasis.opendocument.graphics|odh:text/plain|odi:a",
  "pplication/vnd.oasis.opendocument.image|odl:text/plain|odm:application/vnd.oasis.opendocument.text-master|od",
  "p:application/vnd.oasis.opendocument.presentation|ods:application/vnd.oasis.opendocument.spreadsheet|odt:app",
  "lication/vnd.oasis.opendocument.text|oga:audio/ogg|ogg:audio/ogg|ogv:video/ogg|ogx:application/ogg|omdoc:app",
  "lication/omdoc+xml|one:application/onenote|onea:application/onenote|onepkg:application/onenote|onetmp:applic",
  "ation/onenote|onetoc:application/onenote|onetoc2:application/onenote|opf:application/oebps-package+xml|opml:",
  "text/x-opml|oprc:application/vnd.palm|opus:audio/ogg|orderedtest:application/xml|orf:image/x-olympus-orf|org",
  ":application/vnd.lotus-organizer|osdx:application/opensearchdescription+xml|osf:application/vnd.yamaha.opens",
  "coreformat|otf:application/font-sfnt|oth:application/vnd.oasis.opendocument.text-web|ott:application/vnd.oas",
  "is.opendocument.text-template|ova:application/x-virtualbox-ova|ovf:application/x-virtualbox-ovf|oxps:applica",
  "tion/oxps|oxt:application/vnd.openofficeorg.extension|p:text/x-pascal|p10:application/pkcs10|p12:application",
  "/x-pkcs12|p7b:application/x-pkcs7-certificates|p7c:application/pkcs7-mime|p7m:application/pkcs7-mime|p7r:app",
  "lication/x-pkcs7-certreqresp|p7s:application/pkcs7-signature|p8:application/pkcs8|pac:application/x-ns-proxy",
  "-autoconfig|parquet:application/vnd.apache.parquet|pas:text/x-pascal|paw:application/vnd.pawaafile|pbd:appli",
  "cation/vnd.powerbuilder6|pbm:image/x-portable-bitmap|pcap:application/vnd.tcpdump.pcap|pcast:application/x-p",
  "odcast|pcf:application/x-font-pcf|pcl:application/vnd.hp-pcl|pclxl:application/vnd.hp-pclxl|pct:image/pict|p",
  "curl:application/vnd.curl.pcurl|pcx:application/octet-stream|pcz:application/octet-stream|pdb:application/vn",
  "d.palm|pde:text/x-processing|pdf:application/pdf|pef:image/x-pentax-pef|pem:application/x-x509-ca-cert|pfa:a",
  "pplication/x-font-type1|pfb:application/octet-stream|pfm:application/octet-stream|pfr:application/font-tdpfr",
  "|pfx:application/x-pkcs12|pgm:image/x-portable-graymap|pgn:application/x-chess-pgn|pgp:application/pgp-encry",
  "pted|php:application/x-httpd-php|pic:image/pict|pict:image/pict|pkg:application/octet-stream|pkgdef:text/pla",
  "in|pkgundef:text/plain|pki:application/pkixcmp|pkipath:application/pkix-pkipath|pko:application/vnd.ms-pki.p",
  "ko|pkpass:application/vnd.apple.pkpass|pl:application/x-perl|plb:application/vnd.3gpp.pic-bw-large|plc:appli",
  "cation/vnd.mobius.plc|plf:application/vnd.pocketlearn|pls:audio/scpls|pm:application/x-perl|pma:application/",
  "x-perfmon|pmc:application/x-perfmon|pml:application/x-perfmon|pmr:application/x-perfmon|pmw:application/x-pe",
  "rfmon|png:image/png|pnm:image/x-portable-anymap|pnt:image/x-macpaint|pntg:image/x-macpaint|pnz:image/png|por",
  "tpkg:application/vnd.macports.portpkg|pot:application/vnd.ms-powerpoint|ppa:application/vnd.ms-powerpoint|pp",
  "d:application/vnd.cups-ppd|ppm:image/x-portable-pixmap|pps:application/vnd.ms-powerpoint|ppt:application/vnd",
  ".ms-powerpoint|pqa:application/vnd.palm|prc:application/x-mobipocket-ebook|pre:application/vnd.lotus-freelan",
  "ce|prf:application/pics-rules|prm:application/octet-stream|prx:application/octet-stream|ps:application/posts",
  "cript|psb:application/vnd.3gpp.pic-bw-small|psc1:application/PowerShell|psd:application/octet-stream|psess:a",
  "pplication/xml|psf:application/x-font-linux-psf|pskcxml:application/pskc+xml|psm:application/octet-stream|ps",
  "p:application/octet-stream|pst:application/vnd.ms-outlook|ptid:application/vnd.pvi.ptid1|pub:application/x-m",
  "spublisher|pvb:application/vnd.3gpp.pic-bw-var|pwn:application/vnd.3m.post-it-notes|pwz:application/vnd.ms-p",
  "owerpoint|py:text/plain|pya:audio/vnd.ms-playready.media.pya|pyv:video/vnd.ms-playready.media.pyv|qam:applic",
  "ation/vnd.epson.quickanime|qbo:application/vnd.intu.qbo|qfx:application/vnd.intu.qfx|qht:text/x-html-inserti",
  "on|qhtm:text/x-html-insertion|qps:application/vnd.publishare-delta-tree|qt:video/quicktime|qti:image/x-quick",
  "time|qtif:image/x-quicktime|qtl:application/x-quicktimeplayer|qwd:application/vnd.quark.quarkxpress|qwt:appl",
  "ication/vnd.quark.quarkxpress|qxb:application/vnd.quark.quarkxpress|qxd:application/octet-stream|qxl:applica",
  "tion/vnd.quark.quarkxpress|qxt:application/vnd.quark.quarkxpress|ra:audio/x-pn-realaudio|raf:image/x-fuji-ra",
  "f|ram:audio/x-pn-realaudio|raml:application/raml+yaml|rar:application/x-rar-compressed|ras:image/x-cmu-raste",
  "r|rat:application/rat-file|raw:image/x-panasonic-rw|rc:text/plain|rc2:text/plain|rcprofile:application/vnd.i",
  "punplugged.rcprofile|rct:text/plain|rdf:application/rdf+xml|rdlc:application/xml|rdz:application/vnd.data-vi",
  "sion.rdz|reg:text/plain|rep:application/vnd.businessobjects|res:application/x-dtbresource+xml|resx:applicati",
  "on/xml|rf:image/vnd.rn-realflash|rgb:image/x-rgb|rgs:text/plain|rif:application/reginfo+xml|rip:audio/vnd.ri",
  "p|ris:application/x-research-info-systems|rl:application/resource-lists+xml|rlc:image/vnd.fujixerox.edmics-r",
  "lc|rld:application/resource-lists-diff+xml|rm:application/vnd.rn-realmedia|rmi:audio/mid|rmp:application/vnd",
  ".rn-rn_music_package|rms:application/vnd.jcp.javame.midlet-rms|rmvb:application/vnd.rn-realmedia-vbr|rnc:app",
  "lication/relax-ng-compact-syntax|rng:application/xml|roa:application/rpki-roa|roff:application/x-troff|rp9:a",
  "pplication/vnd.cloanto.rp9|rpm:audio/x-pn-realaudio-plugin|rpss:application/vnd.nokia.radio-presets|rpst:app",
  "lication/vnd.nokia.radio-preset|rq:application/sparql-query|rqy:text/x-ms-rqy|rs:text/x-rust|rsd:application",
  "/rsd+xml|rss:application/rss+xml|rtf:application/rtf|rtx:text/richtext|ruleset:application/xml|run:applicati",
  "on/x-makeself|rvt:application/octet-stream|rw2:image/x-panasonic-rw2|rwl:image/x-panasonic-rw2|s:text/plain|",
  "s3m:audio/s3m|saf:application/vnd.yamaha.smaf-audio|safariextz:application/x-safari-safariextz|sass:text/x-s",
  "ass|sbml:application/sbml+xml|sc:application/vnd.ibm.secure-container|scd:application/x-msschedule|scm:appli",
  "cation/vnd.lotus-screencam|scq:application/scvp-cv-request|scr:text/plain|scs:application/scvp-cv-response|s",
  "css:text/x-scss|sct:text/scriptlet|scurl:text/vnd.curl.scurl|sd2:audio/x-sd2|sda:application/vnd.stardivisio",
  "n.draw|sdc:application/vnd.stardivision.calc|sdd:application/vnd.stardivision.impress|sdkd:application/vnd.s",
  "olent.sdkm+xml|sdkm:application/vnd.solent.sdkm+xml|sdp:application/sdp|sdw:application/vnd.stardivision.wri",
  "ter|sea:application/octet-stream|see:application/vnd.seemail|seed:application/vnd.fdsn.seed|sema:application",
  "/vnd.sema|semd:application/vnd.semd|semf:application/vnd.semf|ser:application/java-serialized-object|setpay:",
  "application/set-payment-initiation|setreg:application/set-registration-initiation|settings:application/xml|s",
  "fd-hdstx:application/vnd.hydrostatix.sof-data|sfs:application/vnd.spotfire.sfs|sfv:text/x-sfv|sgi:image/sgi|",
  "sgimb:application/x-sgimb|sgl:application/vnd.stardivision.writer-global|sgm:text/sgml|sgml:text/sgml|sh:app",
  "lication/x-sh|shar:application/x-shar|shex:text/shex|shf:application/shf+xml|shtml:text/html|sid:image/x-mrs",
  "id-image|sig:application/pgp-signature|sil:audio/silk|silo:model/mesh|sis:application/vnd.symbian.install|si",
  "sx:application/vnd.symbian.install|sit:application/x-stuffit|sitemap:application/xml|sitx:application/x-stuf",
  "fitx|skd:application/vnd.koan|skin:application/xml|skm:application/vnd.koan|skp:application/x-koan|skt:appli",
  "cation/vnd.koan|slim:text/slim|slk:application/vnd.ms-excel|slm:text/slim|sln:text/plain|slt:application/vnd",
  ".epson.salt|slupkg-ms:application/x-ms-license|sm:application/vnd.stepmania.stepchart|smd:audio/x-smd|smf:ap",
  "plication/vnd.stardivision.math|smi:application/octet-stream|smil:application/smil+xml|smv:video/x-smv|smx:a",
  "udio/x-smd|smz:audio/x-smd|smzip:application/vnd.stepmania.package|snd:audio/basic|snf:application/x-font-sn",
  "f|snippet:application/xml|snp:application/octet-stream|so:application/octet-stream|sol:text/plain|sor:text/p",
  "lain|spc:application/x-pkcs7-certificates|spf:application/vnd.yamaha.smaf-phrase|spl:application/futuresplas",
  "h|spot:text/vnd.in3d.spot|spp:application/scvp-vp-response|spq:application/scvp-vp-request|spx:audio/ogg|sql",
  ":application/x-sql|sr2:image/x-sony-sr2|src:application/x-wais-source|srf:text/plain|srt:application/x-subri",
  "p|sru:application/sru+xml|srx:application/sparql-results+xml|ssdl:application/ssdl+xml|sse:application/vnd.k",
  "odak-descriptor|ssf:application/vnd.epson.ssf|ssisdeploymentmanifest:text/xml|ssm:application/streamingmedia",
  "|ssml:application/ssml+xml|sst:application/vnd.ms-pki.certstore|st:application/vnd.sailingtracker.track|stc:",
  "application/vnd.sun.xml.calc.template|std:application/vnd.sun.xml.draw.template|step:application/step|stf:ap",
  "plication/vnd.wt.stf|sti:application/vnd.sun.xml.impress.template|stk:application/hyperstudio|stl:applicatio",
  "n/vnd.ms-pki.stl|stp:application/step|str:application/vnd.pg.format|stw:application/vnd.sun.xml.writer.templ",
  "ate|styl:text/stylus|stylus:text/stylus|sub:text/vnd.dvb.subtitle|sus:application/vnd.sus-calendar|susp:appl",
  "ication/vnd.sus-calendar|sv4cpio:application/x-sv4cpio|sv4crc:application/x-sv4crc|svc:application/xml|svd:a",
  "pplication/vnd.svd|svg:image/svg+xml|svgz:image/svg+xml|swa:application/x-director|swf:application/x-shockwa",
  "ve-flash|swi:application/vnd.aristanetworks.swi|sxc:application/vnd.sun.xml.calc|sxd:application/vnd.sun.xml",
  ".draw|sxg:application/vnd.sun.xml.writer.global|sxi:application/vnd.sun.xml.impress|sxm:application/vnd.sun.",
  "xml.math|sxw:application/vnd.sun.xml.writer|t:application/x-troff|t3:application/x-t3vm-image|taglet:applica",
  "tion/vnd.mynfc|tao:application/vnd.tao.intent-module-archive|tar:application/x-tar|tcap:application/vnd.3gpp",
  "2.tcap|tcl:application/x-tcl|teacher:application/vnd.smart.teacher|tei:application/tei+xml|teicorpus:applica",
  "tion/tei+xml|testrunconfig:application/xml|testsettings:application/xml|tex:application/x-tex|texi:applicati",
  "on/x-texinfo|texinfo:application/x-texinfo|text:text/plain|tfi:application/thraud+xml|tfm:application/x-tex-",
  "tfm|tga:image/x-tga|tgz:application/x-compressed|thmx:application/vnd.ms-officetheme|thn:application/octet-s",
  "tream|tif:image/tiff|tiff:image/tiff|tk:application/x-tcl|tlh:text/plain|tli:text/plain|tmo:application/vnd.",
  "tmobile-livetv|toc:application/octet-stream|toml:text/x-toml|torrent:application/x-bittorrent|tpl:applicatio",
  "n/vnd.groove-tool-template|tpt:application/vnd.trid.tpt|tr:application/x-troff|tra:application/vnd.trueapp|t",
  "rig:application/trig|trm:application/x-msterminal|trx:application/xml|ts:video/vnd.dlna.mpeg-tts|tsd:applica",
  "tion/timestamped-data|tsv:text/tab-separated-values|ttc:font/collection|ttf:font/ttf|ttl:text/turtle|tts:vid",
  "eo/vnd.dlna.mpeg-tts|twd:application/vnd.simtech-mindmapper|twds:application/vnd.simtech-mindmapper|txd:appl",
  "ication/vnd.genomatix.tuxedo|txf:application/vnd.mobius.txf|txt:text/plain|u32:application/octet-stream|u8ds",
  "n:message/global-delivery-status|u8hdr:message/global-headers|u8mdn:message/global-disposition-notification|",
  "u8msg:message/global|udeb:application/x-debian-package|ufd:application/vnd.ufdl|ufdl:application/vnd.ufdl|ul",
  "s:text/iuls|ulx:application/x-glulx|umj:application/vnd.umajin|unityweb:application/vnd.unity|uoml:applicati",
  "on/vnd.uoml+xml|uri:text/uri-list|uris:text/uri-list|urls:text/uri-list|user:text/plain|ustar:application/x-",
  "ustar|utz:application/vnd.uiq.theme|uu:text/x-uuencode|uva:audio/vnd.dece.audio|uvd:application/vnd.dece.dat",
  "a|uvf:application/vnd.dece.data|uvg:image/vnd.dece.graphic|uvh:video/vnd.dece.hd|uvi:image/vnd.dece.graphic|",
  "uvm:video/vnd.dece.mobile|uvp:video/vnd.dece.pd|uvs:video/vnd.dece.sd|uvt:application/vnd.dece.ttml+xml|uvu:",
  "video/vnd.uvvu.mp4|uvv:video/vnd.dece.video|uvva:audio/vnd.dece.audio|uvvd:application/vnd.dece.data|uvvf:ap",
  "plication/vnd.dece.data|uvvg:image/vnd.dece.graphic|uvvh:video/vnd.dece.hd|uvvi:image/vnd.dece.graphic|uvvm:",
  "video/vnd.dece.mobile|uvvp:video/vnd.dece.pd|uvvs:video/vnd.dece.sd|uvvt:application/vnd.dece.ttml+xml|uvvu:",
  "video/vnd.uvvu.mp4|uvvv:video/vnd.dece.video|uvvx:application/vnd.dece.unspecified|uvvz:application/vnd.dece",
  ".zip|uvx:application/vnd.dece.unspecified|uvz:application/vnd.dece.zip|vb:text/plain|vbdproj:text/plain|vbk:",
  "video/mpeg|vbox:application/x-virtualbox-vbox|vbox-extpack:application/x-virtualbox-vbox-extpack|vbproj:text",
  "/plain|vbs:text/vbscript|vcard:text/vcard|vcd:application/x-cdlink|vcf:text/x-vcard|vcg:application/vnd.groo",
  "ve-vcard|vcproj:application/xml|vcs:text/plain|vcx:application/vnd.vcx|vcxproj:application/xml|vddproj:text/",
  "plain|vdi:application/x-virtualbox-vdi|vdp:text/plain|vdproj:text/plain|vdx:application/vnd.ms-visio.viewer|",
  "vhd:application/x-virtualbox-vhd|vis:application/vnd.visionary|viv:video/vnd.vivo|vmdk:application/x-virtual",
  "box-vmdk|vml:text/xml|vob:video/x-ms-vob|vor:application/vnd.stardivision.writer|vox:application/x-authorwar",
  "e-bin|vrml:model/vrml|vscontent:application/xml|vsct:text/xml|vsd:application/vnd.visio|vsf:application/vnd.",
  "vsf|vsi:application/ms-vsi|vsix:application/vsix|vsixlangpack:text/xml|vsixmanifest:text/xml|vsmdi:applicati",
  "on/xml|vspscc:text/plain|vss:application/vnd.visio|vsscc:text/plain|vssettings:text/xml|vssscc:text/plain|vs",
  "t:application/vnd.visio|vstemplate:text/xml|vsto:application/x-ms-vsto|vsw:application/vnd.visio|vsx:applica",
  "tion/vnd.visio|vtt:text/vtt|vtu:model/vnd.vtu|vtx:application/vnd.visio|vxml:application/voicexml+xml|w3d:ap",
  "plication/x-director|wad:application/x-doom|wadl:application/vnd.sun.wadl+xml|war:application/java-archive|w",
  "asm:application/wasm|wav:audio/wav|wave:audio/wav|wax:audio/x-ms-wax|wbk:application/msword|wbmp:image/vnd.w",
  "ap.wbmp|wbs:application/vnd.criticaltools.wbs+xml|wbxml:application/vnd.wap.wbxml|wcm:application/vnd.ms-wor",
  "ks|wdb:application/vnd.ms-works|wdp:image/vnd.ms-photo|weba:audio/webm|webapp:application/x-web-app-manifest",
  "+json|webarchive:application/x-safari-webarchive|webm:video/webm|webmanifest:application/manifest+json|webp:",
  "image/webp|webtest:application/xml|wg:application/vnd.pmi.widget|wgt:application/widget|wiq:application/xml|",
  "wiz:application/msword|wks:application/vnd.ms-works|wlmp:application/wlmoviemaker|wlpginstall:application/x-",
  "wlpg-detect|wlpginstall3:application/x-wlpg3-detect|wm:video/x-ms-wm|wma:audio/x-ms-wma|wmd:application/x-ms",
  "-wmd|wmf:application/x-msmetafile|wml:text/vnd.wap.wml|wmlc:application/vnd.wap.wmlc|wmls:text/vnd.wap.wmlsc",
  "ript|wmlsc:application/vnd.wap.wmlscriptc|wmp:video/x-ms-wmp|wmv:video/x-ms-wmv|wmx:video/x-ms-wmx|wmz:appli",
  "cation/x-ms-wmz|woff:application/font-woff|woff2:font/woff2|wpd:application/vnd.wordperfect|wpl:application/",
  "vnd.ms-wpl|wps:application/vnd.ms-works|wqd:application/vnd.wqd|wri:application/x-mswrite|wrl:x-world/x-vrml",
  "|wrz:x-world/x-vrml|wsc:text/scriptlet|wsdl:text/xml|wspolicy:application/wspolicy+xml|wtb:application/vnd.w",
  "ebturbo|wvx:video/x-ms-wvx|x:application/directx|x32:application/x-authorware-bin|x3d:model/x3d+xml|x3db:mod",
  "el/x3d+binary|x3dbz:model/x3d+binary|x3dv:model/x3d+vrml|x3dvz:model/x3d+vrml|x3dz:model/x3d+xml|x3f:image/x",
  "-sigma-x3f|xaf:x-world/x-vrml|xaml:application/xaml+xml|xap:application/x-silverlight-app|xar:application/vn",
  "d.xara|xbap:application/x-ms-xbap|xbd:application/vnd.fujixerox.docuworks.binder|xbm:image/x-xbitmap|xdf:app",
  "lication/xcap-diff+xml|xdm:application/vnd.syncml.dm+xml|xdp:application/vnd.adobe.xdp+xml|xdr:text/plain|xd",
  "ssc:application/dssc+xml|xdw:application/vnd.fujixerox.docuworks|xenc:application/xenc+xml|xer:application/p",
  "atch-ops-error+xml|xfdf:application/vnd.adobe.xfdf|xfdl:application/vnd.xfdl|xht:application/xhtml+xml|xhtml",
  ":application/xhtml+xml|xhvml:application/xv+xml|xif:image/vnd.xiff|xla:application/vnd.ms-excel|xlam:applica",
  "tion/vnd.ms-excel.addin.macroEnabled.12|xlc:application/vnd.ms-excel|xld:application/vnd.ms-excel|xlf:applic",
  "ation/x-xliff+xml|xlk:application/vnd.ms-excel|xll:application/vnd.ms-excel|xlm:application/vnd.ms-excel|xls",
  ":application/vnd.ms-excel|xlsm:application/vnd.ms-excel.sheet.macroEnabled.12|xlt:application/vnd.ms-excel|x",
  "lw:application/vnd.ms-excel|xm:audio/xm|xml:text/xml|xmp:application/octet-stream|xmta:application/xml|xo:ap",
  "plication/vnd.olpc-sugar|xof:x-world/x-vrml|xoml:text/plain|xop:application/xop+xml|xpi:application/x-xpinst",
  "all|xpl:application/xproc+xml|xpm:image/x-xpixmap|xpr:application/vnd.is-xpr|xps:application/vnd.ms-xpsdocum",
  "ent|xpw:application/vnd.intercon.formnet|xpx:application/vnd.intercon.formnet|xrm-ms:text/xml|xsc:applicatio",
  "n/xml|xsd:text/xml|xsf:text/xml|xsl:text/xml|xslt:text/xml|xsm:application/vnd.syncml+xml|xsn:application/oc",
  "tet-stream|xspf:application/xspf+xml|xss:application/xml|xtp:application/octet-stream|xul:application/vnd.mo",
  "zilla.xul+xml|xvm:application/xv+xml|xvml:application/xv+xml|xwd:image/x-xwindowdump|xyz:chemical/x-xyz|xz:a",
  "pplication/x-xz|yaml:text/x-yaml|yang:application/yang|yin:application/yin+xml|yml:text/x-yaml|ymp:text/x-su",
  "se-ymp|z:application/x-compress|z1:application/x-zmachine|z2:application/x-zmachine|z3:application/x-zmachin",
  "e|z4:application/x-zmachine|z5:application/x-zmachine|z6:application/x-zmachine|z7:application/x-zmachine|z8",
  ":application/x-zmachine|zaz:application/vnd.zzazz.deck+xml|zip:application/zip|zir:application/vnd.zul|zirz:",
  "application/vnd.zul|zmm:application/vnd.handheld-entertainment+xml",
].join("");

const TABLE = new Map<string, string>(
  PACKED.split("|").map((entry) => {
    const cut = entry.indexOf(":");
    return [entry.slice(0, cut), entry.slice(cut + 1)] as [string, string];
  }),
);

/** The extension of `path`, lower-cased, or `""` when it has none. */
function extensionOf(path: string): string {
  const cut = Math.max(path.lastIndexOf("/"), path.lastIndexOf("\\"));
  const name = path.slice(cut + 1);
  const dot = name.lastIndexOf(".");
  // A leading dot is the whole name of a dotfile, not an extension, which is
  // how `Path::extension` reads `.env`.
  return dot <= 0 ? "" : name.slice(dot + 1).toLowerCase();
}

/** `mime_guess::from_path(path).first_or_text_plain().essence_str()`. */
export function mimeOrTextPlain(path: string): string {
  return TABLE.get(extensionOf(path)) ?? "text/plain";
}

/** `mime_guess::from_path(path).first_or_octet_stream().essence_str()`. */
export function mimeOrOctetStream(path: string): string {
  return TABLE.get(extensionOf(path)) ?? "application/octet-stream";
}

/** What the editor node can show a file as, besides text. */
export type MediaPreview = "image" | "video" | "audio" | "pdf";

/**
 * Formats the page's own `<video>` / `<audio>` can decode. A container the
 * engine does not play (`.avi`, `.mkv`) would open as a black box with a
 * spinner, so those stay downloads rather than becoming a preview that lies.
 */
const PLAYABLE_VIDEO = new Set([
  "video/mp4",
  "video/webm",
  "video/ogg",
  "video/quicktime",
  "video/x-m4v",
]);
const PLAYABLE_AUDIO = new Set([
  "audio/mpeg",
  "audio/mp3",
  "audio/wav",
  "audio/x-wav",
  "audio/wave",
  "audio/ogg",
  "audio/flac",
  "audio/aac",
  "audio/mp4",
  "audio/m4a",
  "audio/x-m4a",
  "audio/webm",
]);

/**
 * The media preview for a MIME type from {@link mimeOrOctetStream}, or
 * `undefined` for anything that is text or a download. Images keep their old
 * rule — every `image/*` — because the `<img>` fallback to a download card is
 * already how an undecodable one is handled.
 */
export function mediaPreviewOf(mime: string): MediaPreview | undefined {
  if (mime.startsWith("image/")) return "image";
  if (PLAYABLE_VIDEO.has(mime)) return "video";
  if (PLAYABLE_AUDIO.has(mime)) return "audio";
  if (mime === "application/pdf") return "pdf";
  return undefined;
}
